compressed sparse graph

In [30]:
import scipy
import numpy as np
from scipy.sparse import csr_matrix

In [1]:
from scipy.sparse import csgraph

In [3]:
help(csgraph)

Help on package scipy.sparse.csgraph in scipy.sparse:

NAME
    scipy.sparse.csgraph

DESCRIPTION
    Compressed Sparse Graph Routines (:mod:`scipy.sparse.csgraph`)
    
    .. currentmodule:: scipy.sparse.csgraph
    
    Fast graph algorithms based on sparse matrix representations.
    
    Contents
    
    .. autosummary::
       :toctree: generated/
    
       connected_components -- determine connected components of a graph
       laplacian -- compute the laplacian of a graph
       shortest_path -- compute the shortest path between points on a positive graph
       dijkstra -- use Dijkstra's algorithm for shortest path
       floyd_warshall -- use the Floyd-Warshall algorithm for shortest path
       bellman_ford -- use the Bellman-Ford algorithm for shortest path
       johnson -- use Johnson's algorithm for shortest path
       breadth_first_order -- compute a breadth-first order of nodes
       depth_first_order -- compute a depth-first order of nodes
       breadth_first_tr

# Functions 

In [5]:
dir(csgraph)

['NegativeCycleError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_laplacian',
 '_min_spanning_tree',
 '_reordering',
 '_shortest_path',
 '_tools',
 '_traversal',
 '_validation',
 'absolute_import',
 'bellman_ford',
 'breadth_first_order',
 'breadth_first_tree',
 'connected_components',
 'construct_dist_matrix',
 'csgraph_from_dense',
 'csgraph_from_masked',
 'csgraph_masked_from_dense',
 'csgraph_to_dense',
 'csgraph_to_masked',
 'depth_first_order',
 'depth_first_tree',
 'dijkstra',
 'division',
 'floyd_warshall',
 'johnson',
 'laplacian',
 'maximum_bipartite_matching',
 'minimum_spanning_tree',
 'print_function',
 'reconstruct_path',
 'reverse_cuthill_mckee',
 'shortest_path',
 'structural_rank',
 'test']

# Convert array to compressed sparse row matrix

In [13]:
from scipy.sparse import csr_matrix

```python
Init signature: csr_matrix(arg1, shape=None, dtype=None, copy=False)
Docstring:     
Compressed Sparse Row matrix

This can be instantiated in several ways:
    csr_matrix(D)
        with a dense matrix or rank-2 ndarray D

    csr_matrix(S)
        with another sparse matrix S (equivalent to S.tocsr())

    csr_matrix((M, N), [dtype])
        to construct an empty matrix with shape (M, N)
        dtype is optional, defaulting to dtype='d'.

    csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])
        where ``data``, ``row_ind`` and ``col_ind`` satisfy the
        relationship ``a[row_ind[k], col_ind[k]] = data[k]``.

    csr_matrix((data, indices, indptr), [shape=(M, N)])
        is the standard CSR representation where the column indices for
        row i are stored in ``indices[indptr[i]:indptr[i+1]]`` and their
        corresponding values are stored in ``data[indptr[i]:indptr[i+1]]``.
        If the shape parameter is not supplied, the matrix dimensions
        are inferred from the index arrays.

Attributes
----------
dtype : dtype
    Data type of the matrix
shape : 2-tuple
    Shape of the matrix
ndim : int
    Number of dimensions (this is always 2)
nnz
    Number of nonzero elements
data
    CSR format data array of the matrix
indices
    CSR format index array of the matrix
indptr
    CSR format index pointer array of the matrix
has_sorted_indices
    Whether indices are sorted

Notes
-----

Sparse matrices can be used in arithmetic operations: they support
addition, subtraction, multiplication, division, and matrix power.

Advantages of the CSR format
  - efficient arithmetic operations CSR + CSR, CSR * CSR, etc.
  - efficient row slicing
  - fast matrix vector products

Disadvantages of the CSR format
  - slow column slicing operations (consider CSC)
  - changes to the sparsity structure are expensive (consider LIL or DOK)

```

<b style='color:red'>To convert <code>CSR</code> to array: <code>CSR.toarray()</code></b>

In [23]:
#create an empty matrix of shape 5 x 5
csr_matrix((5,5), dtype = np.int8).toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [27]:
#directed graph, u[i] connects v[i] with weight w[i]
u = np.array([0, 0, 1, 2, 2, 2])
v = np.array([0, 2, 2, 0, 1, 2])
w = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((w, (u,v)), dtype = np.int8, shape = (3,3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int8)

In [34]:
#convert array to CSR
adj = np.random.randint(0, 2, (3,3))
print('Array:\n', adj, '\n')
CSR = csr_matrix(adj)
print('CSR:\n', CSR)

Array:
 [[0 0 1]
 [0 1 0]
 [0 1 1]] 

CSR:
   (0, 2)	1
  (1, 1)	1
  (2, 1)	1
  (2, 2)	1


In [39]:
# the column indices for row i are stored in ``indices[indptr[i]:indptr[i+1]]`` and their
# corresponding values are stored in ``data[indptr[i]:indptr[i+1]]``
#node 0 connects to nodes 0, 2 with weights 1, 2 respectively (indices[0:2] with weights data[0:2])
                                       #u| 0          |      1      | 2
indptr = np.array([0, 2, 3, 6])        # |0:2         |    2:3      | 3:6
indices = np.array([0, 2, 2, 0, 1, 2]) #v|indices[0:2]| indices[2:3]| indices[3:6]
data = np.array([1, 2, 3, 4, 5, 6])    #w|data[0:2]   | data[2:3]   | data[3:6] 
csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()

#row 0: 

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

Practice: Convert to csr_matrix using 3 different ways

In [40]:
#mat[u] contains a list of (v, w) : node u connects node v with weight w
mat = [
    [(2,1)],
    [(0,5), 
     (2,5)],
    [(0,8)]
]

In [41]:
#Using csr_matrix((data, indices, indptr))
indptr = np.r_[0, np.cumsum([len(v) for v in mat])]

temp = np.vstack(mat)

indices, data = temp[:,0], temp[:,1]


csr_matrix((data, indices, indptr), shape = (3,3)).toarray()

array([[0, 0, 1],
       [5, 0, 5],
       [8, 0, 0]])

In [48]:
#using csr_matrix((w, (u,v)))
v, w = np.vstack(mat).T
u = np.concatenate([[i] * len(v) for i, v in enumerate(mat)])
csr_matrix((w, (u,v)), shape = (3,3)).toarray()


array([[0, 0, 1],
       [5, 0, 5],
       [8, 0, 0]], dtype=int32)

In [51]:
#using csr_matrix(graph)
graph = np.zeros((3,3))

for u in range(3):
    for v, w in mat[u]:
        graph[u,v] = w

csr_matrix(graph, dtype = np.int, shape = (3,3)).toarray() 

array([[0, 0, 1],
       [5, 0, 5],
       [8, 0, 0]], dtype=int32)

# Review some funtions

In [41]:
from scipy.sparse.csgraph import dijkstra, bellman_ford, floyd_warshall, minimum_spanning_tree 

## Dijkstra

```python
dijkstra(csgraph, directed=True, indices=None, return_predecessors=False,
         unweighted=False, limit=np.inf)

Dijkstra algorithm using Fibonacci Heaps

.. versionadded:: 0.11.0

Parameters
----------
csgraph : array, matrix, or sparse matrix, 2 dimensions
    The N x N array of non-negative distances representing the input graph.
directed : bool, optional
    If True (default), then find the shortest path on a directed graph:
    only move from point i to point j along paths csgraph[i, j] and from 
    point j to i along paths csgraph[j, i].
    If False, then find the shortest path on an undirected graph: the
    algorithm can progress from point i to j or j to i along either 
    csgraph[i, j] or csgraph[j, i].
indices : array_like or int, optional
    if specified, only compute the paths for the points at the given
    indices.
return_predecessors : bool, optional
    If True, return the size (N, N) predecesor matrix
unweighted : bool, optional
    If True, then find unweighted distances.  That is, rather than finding
    the path between each point such that the sum of weights is minimized,
    find the path such that the number of edges is minimized.
limit : float, optional
    The maximum distance to calculate, must be >= 0. Using a smaller limit
    will decrease computation time by aborting calculations between pairs
    that are separated by a distance > limit. For such pairs, the distance
    will be equal to np.inf (i.e., not connected).

    .. versionadded:: 0.14.0

Returns
-------
dist_matrix : ndarray
    The matrix of distances between graph nodes. dist_matrix[i,j]
    gives the shortest distance from point i to point j along the graph.

predecessors : ndarray
    Returned only if return_predecessors == True.
    The matrix of predecessors, which can be used to reconstruct
    the shortest paths.  Row i of the predecessor matrix contains
    information on the shortest paths from point i: each entry
    predecessors[i, j] gives the index of the previous node in the
    path from point i to point j.  If no path exists between point
    i and j, then predecessors[i, j] = -9999

Notes
-----
As currently implemented, Dijkstra's algorithm does not work for
graphs with direction-dependent distances when directed == False.
i.e., if csgraph[i,j] and csgraph[j,i] are not equal and
both are nonzero, setting directed=False will not yield the correct
result.

Also, this routine does not work for graphs with negative
distances.  Negative distances can lead to infinite cycles that must
be handled by specialized algorithms such as Bellman-Ford's algorithm
or Johnson's algorithm.
```

You have a strongly connected directed graph that has positive weights in the adjacency matrix `g`. The graph is represented as a square matrix, where `g[i][j]` is the weight of the edge `(i, j)`, or 0 if there is no such edge.

Given`g` and the index of a start vertex `s`, find the minimal distances between the start vertex `s` and each of the vertices of the graph.


In [63]:
g = np.array([
  [0,3,2], 
  [2,0,0], 
  [0,0,0]], dtype = np.float64
)

s = 0

In [64]:
distance, reconstruction_path = dijkstra(g, directed = True, indices = s, return_predecessors = True)
distance

array([0., 3., 2.])

In [65]:
reconstruction_path

array([-9999,     0,     0])

## Bellman Ford

```python
bellman_ford(csgraph, directed=True, indices=None, return_predecessors=False,
             unweighted=False)
```

In [66]:
bellman_ford(g, indices = s)

array([0., 3., 2.])

# Floyd Wharshall

```python
floyd_warshall(csgraph, directed=True, return_predecessors=False,
               unweighted=False, overwrite=False)
```

In [67]:
floyd_warshall(g)

array([[ 0.,  3.,  2.],
       [ 2.,  0.,  4.],
       [inf, inf,  0.]])

# minimum spanning tree

```python
minimum_spanning_tree(csgraph, overwrite=False)
```

```python
Returns
-------
span_tree : csr matrix
    The N x N compressed-sparse representation of the undirected minimum
    spanning tree over the input (see notes below).
```