In [1]:
from scipy.fftpack import fft, ifft

In [2]:
#fft: fast fourier transform
#ifft: inverse fast fourier transform

In [3]:
import numpy as np

In [16]:
np.random.seed(42)
Activations = np.random.randint(1, 10, 10)
Filter = np.random.randint(1, 10, 3)

In [26]:
Filter

array([8, 8, 3])

In [27]:
fft(Filter)

array([19. +0.j        ,  2.5-4.33012702j,  2.5+4.33012702j])

In [28]:
ifft(fft(Filter))

array([8.+0.j, 8.+0.j, 3.+0.j])