In [2]:
library(tidyverse)

# Extract matched groups from a string

```r
str_match(string, pattern)     # (Match[0], Match.groups()) where Match = re.search(pattern, string)

str_match_all(string, pattern) # (Match[0], Match.groups()) for Match in re.finditer(pattern, string)
```

# Value

For **`str_match`**, a character matrix. First column is the complete match, followed by one column for each capture group.  
For **`str_match_all`**, a list of character matrices.

# Examples

In [5]:
pattern <- '([A-Za-z]+)\\W*(\\d*)'

In [8]:
'VN Pikachu' %>% str_match(pattern)

[,1] [,2] [,3]
[1,] VN   VN

In [9]:
'Meomeo888' %>% str_match(pattern)

[,1]      [,2]   [,3]
[1,] Meomeo888 Meomeo 888

In [10]:
'David666 Galski9999' %>% str_match(pattern)

[,1]     [,2]  [,3]
[1,] David666 David 666

<hr>

In [11]:
'David666 Galski9999' %>% str_match_all(pattern)

[[1]]
     [,1]         [,2]     [,3]  
[1,] "David666"   "David"  "666" 
[2,] "Galski9999" "Galski" "9999"

Vectorize

In [15]:
players <- c('VN Pikachu', 'Meomeo888', 'soso-777-', 'VNC Son La TF', 'VN Wanie', 'Davi666 Galski999')

In [16]:
players %>% str_match(pattern)

[,1]      [,2]   [,3]
[1,] VN        VN         
[2,] Meomeo888 Meomeo 888 
[3,] soso-777  soso   777 
[4,] VNC       VNC        
[5,] VN        VN         
[6,] Davi666   Davi   666

In [18]:
# Return a list of matrix
players %>% str_match_all(pattern)

[[1]]
     [,1]      [,2]      [,3]
[1,] "VN "     "VN"      ""  
[2,] "Pikachu" "Pikachu" ""  

[[2]]
     [,1]        [,2]     [,3] 
[1,] "Meomeo888" "Meomeo" "888"

[[3]]
     [,1]       [,2]   [,3] 
[1,] "soso-777" "soso" "777"

[[4]]
     [,1]   [,2]  [,3]
[1,] "VNC " "VNC" ""  
[2,] "Son " "Son" ""  
[3,] "La "  "La"  ""  
[4,] "TF"   "TF"  ""  

[[5]]
     [,1]    [,2]    [,3]
[1,] "VN "   "VN"    ""  
[2,] "Wanie" "Wanie" ""  

[[6]]
     [,1]        [,2]     [,3] 
[1,] "Davi666"   "Davi"   "666"
[2,] "Galski999" "Galski" "999"