Arrays are the R data objects which can store data in more than two dimensions.

**Usage**

```R
array(data = NA, dim = length(data), dimnames = NULL)
as.array(x, ...)
is.array(x)
```

# Array creation

In [5]:

# Create two vectors of different lengths.
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

# Take these vectors as input to the array.
result <- array(c(vector1,vector2),dim = c(3,3,2))
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



In [8]:
print(array(c(1,2,3,4), dim = c(2,2,2)))

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    1    3
[2,]    2    4



<hr>

You can also change the shape of array using **`dim()`**

In [11]:
arr <- array(1:12)
arr

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [13]:
#changing shape
dim(arr) <- c(2,3,2)
print(arr)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12



<hr>

adding names for dimensions using **`dimnames`**

In [17]:
dimnames(arr) <- list(c('a', 'b'), c('1', '2', '3'), c('channel 1', 'channel 2'))
print(arr)

, , channel 1

  1 2 3
a 1 3 5
b 2 4 6

, , channel 2

  1  2  3
a 7  9 11
b 8 10 12



# Getting the number of rows and columns of an array

`nrow` and `ncol` return the number of rows or columns present in x. `NCOL` and `NROW` do the same treating a vector as 1-column matrix, even a 0-length vector, compatibly with

In [1]:
mat <- matrix(1:12, 3, 4)

nrow(mat)

[1] 3

In [2]:
ncol(mat)

[1] 4

In [3]:
# 1:12 is neither an array or matrix so return null
nrow(1:12)

NULL

In [4]:
#but we can use NROW and NCOL to treat a vector a matrix of shape (n, 1)
NROW(1:12)

[1] 12

In [5]:
NCOL(1:12)

[1] 1

# Naming Columns and Rows

In [2]:
row = c('row1', 'row2')
col = c('col1', 'col2')
mat = c('mat1', 'mat2')
res = array(c(1,2,3,4), dim = c(2,2,2), dimnames = list(row, col, mat))
print(res)

, , mat1

     col1 col2
row1    1    3
row2    2    4

, , mat2

     col1 col2
row1    1    3
row2    2    4



# Accessing Array elements

In [3]:
#print the second matrix
res[,,2]

col1 col2
row1 1    3   
row2 2    4

In [4]:
# Print the first row of the second matrix of the array.
res[1,,2]

col1 col2 
   1    3

In [5]:
#accessing using attribute
res[,,'mat2']

col1 col2
row1 1    3   
row2 2    4

# Manipulation

# Calculation accross array elements

```R
apply(x, margin, fun)
```

Parameters:  
* **`x`** is an array.

* **`margin`** is the name of the data set used.

* **`fun`** is the function to be applied across the elements of the array.

In [6]:

new.array <- array(1:8, dim = c(2, 2, 2))
print(new.array)

# Use apply to calculate the sum of the rows across all the matrices.
result <- apply(new.array, c(1), sum)
print(result)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

[1] 16 20
