In [7]:
library(tidyverse)

**`unlist`**: flatten list. It is able to flatten a deeply nested list. This is more powerful that **`purrr:as_vector`**, which only flattens a single layer.

In [2]:
args(unlist)

function (x, recursive = TRUE, use.names = TRUE) 
NULL

In [4]:
deeply_nested <- list(list(list(1, 2), list(3, 4)))

unlist(deeply_nested)

[1] 1 2 3 4

---


**`unname`**: return a new object with `names` attribute is removed 

In [5]:
player <- list(name = 'VN Pikachu', level = 31)

unname(player)

[[1]]
[1] "VN Pikachu"

[[2]]
[1] 31

In [1]:
# source code
unname

function (obj, force = FALSE) 
{
    if (!is.null(names(obj))) 
        names(obj) <- NULL
    if (!is.null(dimnames(obj)) && (force || !is.data.frame(obj))) 
        dimnames(obj) <- NULL
    obj
}
<bytecode: 0x55e042a90b78>
<environment: namespace:base>

This return a new object instead of modifying inplace, because `obj` is a new object in the executing environment

---

**`apply`**: apply a function over array margins

In [6]:
args(apply)

function (X, MARGIN, FUN, ...) 
NULL

In [7]:
v <- matrix(1:12, nrow = 3)
v

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [8]:
# cumsum for each column
apply(v, MARGIN = 2, cumsum)

[,1] [,2] [,3] [,4]
[1,] 1     4    7   10  
[2,] 3     9   15   21  
[3,] 6    15   24   33

In [9]:
# mean for each row
apply(v, MARGIN = 1, mean)

[1] 5.5 6.5 7.5

In [12]:
# apply a function for every element

apply(v, MARGIN = c(1, 2), sqrt)

[,1]     [,2]     [,3]     [,4]    
[1,] 1.000000 2.000000 2.645751 3.162278
[2,] 1.414214 2.236068 2.828427 3.316625
[3,] 1.732051 2.449490 3.000000 3.464102

---

**`nchar`**: the length of a string. This is useful than **`stringr::str_length`** is the case of a single string

In [15]:
nchar('Pikachu')  # this returns a single string

stringr::str_length('Pikachu') # this returns a vector of length 1 (because it always vectorize)

[1] 7

[1] 7

In [14]:
nchar(c('Hello', 'World!'))

[1] 5 6

---
**`stringi::stri_reverse()`**

---

**`formals`**: a list of default values for arguments of a function

In [2]:
formals(purrr::pluck)

$.x


$...


$.default
NULL


---
**`body`**: get the code inside the body of a function

In [4]:
body(purrr::pluck)

{
    .Call(pluck_impl, x = .x, index = list2(...), missing = .default, 
        strict = FALSE)
}

---
**`diff()`**

In [1]:
diff(c(2, 5, 8))

[1] 3 3

---
**`rbind`**, **`cbind`**

you can use these functions to add rows, columns to array, matrix, data.frame, ...

---

**`intToUtf8`**

In [1]:
intToUtf8(97) # ascii to character

[1] "a"

**`utf8ToInt`**

In [2]:
utf8ToInt('a') # character to ascii

[1] 97

---
**`chartr`**

In [3]:
args(chartr)

function (old, new, x) 
NULL

In [4]:
# like translate in Python
# change a to 1, b to 2 and c to 3

chartr('abc', '123', 'ccaabb')

[1] "331122"

---
The number of rows/columns of an array


`nrow` and `ncol` return the number of rows or columns present in `x`. `NCOL` and `NROW` do the same treating a vector as 1-column matrix, even a 0-length vector, compatibly with `as.matrix()` or `cbind()`, see the example.

**Usage**

```
nrow(x)
ncol(x)
NCOL(x)
NROW(x)
```

In [3]:
values <- matrix(1:12, nrow = 3)

values

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [5]:
nrow(values)

ncol(values)

[1] 3

[1] 4

In [7]:
nrow(letters)
ncol(letters)

# Use NROW and NCOL for vector
# treat this like a matrix 26 x 1
NROW(letters)
NCOL(letters)

NULL

NULL

[1] 26

[1] 1

In [11]:
nrow(NULL)
ncol(NULL)

# treat as 0 x 1 dimension
NROW(NULL)
NCOL(NULL)

NULL

NULL

[1] 0

[1] 1

---

Base R provides a useful set:

- `integrate()` finds the area under the curve defined by f()
- `uniroot()` finds where f() hits zero
- `optimise()` finds the location of the lowest (or highest) value of f()

In [1]:
integrate(sin, 0, pi)

2 with absolute error < 2.2e-14

In [5]:
str(uniroot(sin, interval = pi * c(1 / 2, 3 / 2)))

List of 5
 $ root      : num 3.14
 $ f.root    : num 1.22e-16
 $ iter      : int 2
 $ init.it   : int NA
 $ estim.prec: num 6.1e-05


In [6]:
# min
str(optimise(sin, c(0, 2 * pi)))

List of 2
 $ minimum  : num 4.71
 $ objective: num -1


In [7]:
# max
str(optimise(sin, c(0, 2 * pi), maximum = T))

List of 2
 $ maximum  : num 1.57
 $ objective: num 1


---
**`stat::complete.cases`**

Create a column in a data frame that return TRUE if a row having missing value

In [2]:
df <- tibble::tribble(
~ x, ~ y,
  1,   2, 
  1,   NA,
  NA,   2,
  NA,   NA)

df

x  y 
1  1  2
2  1 NA
3 NA  2
4 NA NA

In [4]:
complete.cases(df)

[1]  TRUE FALSE FALSE FALSE

In [8]:
df  %>% mutate(anymiss = complete.cases(cur_data()))

x  y  anymiss
1  1  2  TRUE  
2  1 NA FALSE  
3 NA  2 FALSE  
4 NA NA FALSE

---

**`strptime`**

In [4]:
# ?strptime

---
**`match`**

In [11]:
# find position vectorized
match(c('c', 'c', 'a', 'b', '$'), letters)

[1]  3  3  1  2 NA

---
**`match.arg`**

check if an argument is presented in a list

In [12]:
fruits <- c('banana', 'apple', 'orange')
match.arg('apple', fruits)

[1] "apple"

In [13]:
try(match.arg('cucumber', fruits))

Error in match.arg("cucumber", fruits) : 
  'arg' should be one of "banana", "apple", "orange"
