Matrices are the R objects in which the elements are arranged in a two-dimensional rectangular layout. They contain elements of the same atomic types. Though we can create a matrix containing only characters or only logical values, they are not of much use. We use matrices containing numeric elements to be used in mathematical calculations.

`matrix` creates a matrix from the given set of values.

`as.matrix` attempts to turn its argument into a matrix.

`is.matrix` tests if its argument is a (strict) matrix.

# Matrix creation

```R
matrix(data, nrow, ncol, byrow, dimnames)
```

parameters:
* data is the input vector which becomes the data elements of the matrix.

* nrow is the number of rows to be created.

* ncol is the number of columns to be created.

* byrow is a logical clue. If TRUE then the input vector elements are arranged by row.

* dimname is the names assigned to the rows and columns.

In [3]:
#C order in numpy
matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE)

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [1]:
#F order in numpy
matrix(1:12, nrow = 3, ncol = 4, byrow = FALSE)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [2]:
#name for rows and columns
row_names = c('row1', 'row2', 'row3')
col_names = c('col1', 'col2', 'col3', 'col4')

mat = matrix(1:12, nrow = 3, ncol = 4, byrow = TRUE, dimnames = list(row_names, col_names))
mat

col1 col2 col3 col4
row1 1     2    3    4  
row2 5     6    7    8  
row3 9    10   11   12

In [10]:
mat <- matrix(1:12, nrow = 3)
# setting row names and columns names
rownames(mat) <- c('row1', 'row2', 'row3')
colnames(mat) <- c('col1', 'col2', 'col3', 'col4')
mat

col1 col2 col3 col4
row1 1    4    7    10  
row2 2    5    8    11  
row3 3    6    9    12

# Get the number of rows and columns

In [26]:
# number of rows
nrow(mat)

[1] 3

In [27]:
# number of columns
ncol(mat)

[1] 4

# Accessing Elements of a Matrix

In [5]:
mat

col1 col2 col3 col4
row1 1     2    3    4  
row2 5     6    7    8  
row3 9    10   11   12

In [9]:
#value at (2,2) (1-based)
mat[2,2]

[1] 6

In [10]:
#select the 3rd column
mat[,3]

row1 row2 row3 
   3    7   11

In [11]:
# select 2-th, 3-th colum
mat[, c(2, 3)]

col2 col3
row1 4    7   
row2 5    8   
row3 6    9

In [13]:
# do not select 3-th column
mat[, -3]

col1 col2 col4
row1 1    4    10  
row2 2    5    11  
row3 3    6    12

In [12]:
# do not select column 1 and 4
mat[, -c(1, 4)]

col2 col3
row1 4    7   
row2 5    8   
row3 6    9

In [12]:
#select the second row
mat[2,]

col1 col2 col3 col4 
   5    6    7    8

In [18]:
# you can also access columns or rows by name
mat['row1',]  # select row with name 'row1'
mat[, 'col1'] # select column with name 'col1'
mat[1, 'col2'] # select value at row 1, column 'col2'

col1 col2 col3 col4 
   1    4    7   10

row1 row2 row3 
   1    2    3

[1] 4

---

**`drop = FALSE`**

In [1]:
clan <- data.frame(name = c('VN Pikachu', 'Tank Cao'), level = c(31, 35))
clan

name       level
1 VN Pikachu 31   
2 Tank Cao   35

In [2]:
# select a single column in data frame will return a vector
clan[, 2]

[1] 31 35

In [3]:
# if you want to return a data frame with 1 column, set drop = FASLE
clan[, 2, drop = F]

level
1 31   
2 35

# Matrix computation

In [14]:
A = matrix(1:4, nrow = 2, ncol = 2)
A

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [16]:
B = matrix(c(1,0,0,1), nrow = 2, ncol = 2)
B

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [19]:
#addition
A + B

[,1] [,2]
[1,] 2    3   
[2,] 2    5

In [20]:
#subtraction
A - B

[,1] [,2]
[1,] 0    3   
[2,] 2    3

In [22]:
#multiplication (element-wise)
A * B

[,1] [,2]
[1,] 1    0   
[2,] 0    4

In [24]:
#matrix multiplication
A %*% B

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [25]:
#division (element-wise)
B / A

[,1] [,2]
[1,] 1    0.00
[2,] 0    0.25

In [26]:
#remainder (element-wise)
B %% A

[,1] [,2]
[1,] 0    0   
[2,] 0    1

In [27]:
#floor division (element-wise)
B %/% A

[,1] [,2]
[1,] 1    0   
[2,] 0    0

# Checking matrix

**`is.matrix()`**

In [2]:
values <- array(1:9, dim = c(3, 3))
is.matrix(values)

[1] TRUE

In [3]:
is.matrix(1:10)

[1] FALSE

# Converting to matrix

**`as.matrix()`**

In [8]:
mat <- as.matrix(c(5, 2))
mat

[,1]
[1,] 5   
[2,] 2

In [9]:
is.matrix(mat)

[1] TRUE

<hr>

If you wanna convert a vector to a matrix, using the below procedure will avoid duplicating 

```R
dim(x) <- c(nx, ny)
dimnames(x) <- list(row_names, col_names)
```

In [11]:
vec <- 1:6

dim(vec) <- c(2, 3)
dimnames(vec) <- list(c('r1', 'r2'), c('c1', 'c2', 'c3'))
vec

c1 c2 c3
r1 1  3  5 
r2 2  4  6

# Functions with matrix

Form row and column sums and means for numeric arrays (or data frames).

**`colMeans`**, **`colSums`**, **`rowMeans`**, **`rowSums`**, ...

```r
colSums (x, na.rm = FALSE, dims = 1)
rowSums (x, na.rm = FALSE, dims = 1)
colMeans(x, na.rm = FALSE, dims = 1)
rowMeans(x, na.rm = FALSE, dims = 1)
```

In [19]:
mat

col1 col2 col3 col4
row1 1    4    7    10  
row2 2    5    8    11  
row3 3    6    9    12

In [22]:
colSums(mat)

col1 col2 col3 col4 
   6   15   24   33

In [23]:
colMeans(mat)

col1 col2 col3 col4 
   2    5    8   11

In [24]:
rowSums(mat)

row1 row2 row3 
  22   26   30

In [25]:
rowMeans(mat)

row1 row2 row3 
 5.5  6.5  7.5

# Linear Algebra

In [8]:
mat <- matrix(c(1:9), nrow = 3)

In [9]:
# invert a matrix
solve(mat)

ERROR: Error in solve.default(mat): Lapack routine dgesv: system is exactly singular: U[3,3] = 0


In [10]:
# transpose
t(mat)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [11]:
# extract, replace or create diagonal matrix
diag(c(1, 2, 3))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3