# Types of Operators

We have the following types of operators in R programming −

* Arithmetic Operators
* Relational Operators
* Logical Operators
* Assignment Operators
* Miscellaneous Operators

## Arithmetic Operators

In [12]:
#adding 2 vectors
cat.1 = c(1,2,3) + c(4,5,6)
cat.2 = c(0, 0, 0) + 5
cat('cat.1: ', cat.1, '\ncat.2: ', cat.2)

cat.1:  5 7 9 
cat.2:  5 5 5

In [10]:
#subtract 2 vectors (broadcasting)
sub.1 = c(1,2,3) - 1
sub.2 = c(1,2,3) - c(3,2,1)
cat('sub.1: ', sub.1, '\nsub.2: ', sub.2)

sub.1:  0 1 2 
sub.2:  -2 0 2

In [9]:
#multiply
mul.1 = c(1,2,3) * c(3,2,1)
mul.2 = c(1,2,3) * 5
cat('mul.1: ',mul.1, '\nmul.2: ', mul.2)

mul.1:  3 4 3 
mul.2:  5 10 15

In [13]:
#devide
c(5,7,8) / c(2, 1, 3)

[1] 2.500000 7.000000 2.666667

In [15]:
#Give the remainder of the first vector with the second
c(5, 3, 1) %% c(2, 2, 8)

[1] 1 1 1

In [16]:
#The result of division of first vector with second (quotient) (floor division)
c(5, 3) %/% 2

[1] 2 1

In [17]:
#exp
c(5, 2) ^ c(2, 5)

[1] 25 32

## Relational Operators

In [18]:
1 == 1.

[1] TRUE

In [19]:
2 < 3

[1] TRUE

In [20]:
3 > 2

[1] TRUE

In [21]:
c(1, 2, 3) != c(1, 2, 3)

[1] FALSE FALSE FALSE

In [22]:
c(3, 5, 6) >= 5

[1] FALSE  TRUE  TRUE

In [23]:
c(1, 5, 6) <= 5

[1]  TRUE  TRUE FALSE

## Logical Operators

Following table shows the logical operators supported by R language. It is applicable only to vectors of type logical, numeric or complex. All numbers greater than 1 are considered as logical value TRUE.

Each element of the first vector is compared with the corresponding element of the second vector. The result of comparison is a Boolean value.

In [26]:
#logical AND
c(TRUE, TRUE, FALSE) & c(TRUE, FALSE, FALSE)

[1]  TRUE FALSE FALSE

In [27]:
#logical OR
c(TRUE, TRUE, FALSE) | c(TRUE, FALSE, FALSE)

[1]  TRUE  TRUE FALSE

In [31]:
#logical NOT
!c(TRUE, FALSE)

[1] FALSE  TRUE

The logical operator && and || considers only the first element of the vectors and give a vector of single element as output.

In [32]:
c(3, 0, TRUE, 2+2i) && c(1, 3, TRUE, 2+3i)

[1] TRUE

In [33]:
c(0, 0, TRUE, 2+2i) || c(0, 3, TRUE, 2+3i)

[1] FALSE

## Assignment Operators

### Left assignment

In [34]:
a <- 3

In [37]:
a <<- 3L

In [38]:
a = 'Pikachu'

### Right assignment

In [40]:
charToRaw('Milona') -> a
8:10 ->> a


## Miscellaneous Operators

These operators are used to for specific purpose and not general mathematical or logical computation.`

Colon operator: **`:`**  
It creates the series of numbers in sequence for a vector.

In [46]:
8:1

[1] 8 7 6 5 4 3 2 1

In [47]:
3:9

[1] 3 4 5 6 7 8 9

**`%in%`**  
This operator is used to identify if an element belongs to a vector.

In [53]:
5 %in% c(1, 5, 8)

[1] TRUE

In [54]:
'VN Pikachu' %in% c('ARMAGEDON', 'Guest691', 'ETOGRUL')

[1] FALSE

**`%*%`**: Multiply 2 matrices

In [58]:
A <- matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2)
A

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [60]:
B <- matrix(c(1, 0, 0, 1), nrow = 2, ncol = 2)
B

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [63]:
C <- matrix(c(1, 2), nrow = 2, ncol = 1)
C

[,1]
[1,] 1   
[2,] 2

In [62]:
A %*% B

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [65]:
A %*% C

[,1]
[1,]  7  
[2,] 10

In [5]:
# dot product
print(c(1, 2, 3) %*% c(1, 2, 3))

# equivalent
print(crossprod(c(1, 2, 3), 1:3))

     [,1]
[1,]   14
     [,1]
[1,]   14


In [7]:
# outer prodduct
print(c(1, 2, 3) %o% c(1, 2, 3))
# equivalent
print(tcrossprod(1:3, 1:3))

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    6
[3,]    3    6    9
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    2    4    6
[3,]    3    6    9
