In [1]:
c(1L, 2L, 3L)

[1] 1 2 3

In [2]:
c(1.2, 2.3, 3.4)

[1] 1.2 2.3 3.4

In [3]:
c(1 + 2i, 3 + 2i, 5i)

[1] 1+2i 3+2i 0+5i

In [4]:
c('VN Pikachu', 'Meomeo888', 'Tank Cao')

[1] "VN Pikachu" "Meomeo888"  "Tank Cao"

In [6]:
charToRaw('King Allool')

 [1] 4b 69 6e 67 20 41 6c 6c 6f 6f 6c

In [7]:
class(1L)

[1] "integer"

In [8]:
TRUE

[1] TRUE

In [9]:
class(TRUE)

[1] "logical"

In [10]:
class(1.2)

[1] "numeric"

In [11]:
c(1, 2, 3)

[1] 1 2 3

In [12]:
c(c(1,2,3), c(4, 5, 6))

[1] 1 2 3 4 5 6

In [14]:
list(1L, 3.1416, 1i, TRUE, c('Hello World!'), charToRaw('R programming'))

[[1]]
[1] 1

[[2]]
[1] 3.1416

[[3]]
[1] 0+1i

[[4]]
[1] TRUE

[[5]]
[1] "Hello World!"

[[6]]
 [1] 52 20 70 72 6f 67 72 61 6d 6d 69 6e 67


In [17]:
mat = array(1:8, dim = c(2,2,2))
print(mat)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



In [19]:
genders <- c('Male', 'Female', 'Female', 'Male', 'Female')
is.factor(genders)

[1] FALSE

In [23]:
cat <- factor(genders)
cat

[1] Male   Female Female Male   Female
Levels: Female Male

In [24]:
is.factor(cat)

[1] TRUE

In [26]:
matrix(1:12, nrow = 3, ncol = 4, byrow = FALSE, dimnames = list(c('a', 'b', 'c'), c('a', 'b', 'c', 'd')))

a b c d 
a 1 4 7 10
b 2 5 8 11
c 3 6 9 12

In [27]:
player = list('VN Pikachu', 31, c(57611, 2799))
names(player) <- c('Name', 'Level', 'Stats')
player

$Name
[1] "VN Pikachu"

$Level
[1] 31

$Stats
[1] 57611  2799

In [29]:
player$Name

[1] "VN Pikachu"

In [45]:
clan <- data.frame(
    name = c('VN Pikachu', 'Meomeo888', 'Morino Nanako'),
    level = c(31, 32, 34),
    gender = c('Male', 'Male', 'Female'),
    country = c('VN', 'VN', 'JP')
)

clan

name          level gender country
1 VN Pikachu    31    Male   VN     
2 Meomeo888     32    Male   VN     
3 Morino Nanako 34    Female JP

In [42]:
is.factor(clan$gender)

[1] TRUE

In [50]:
'Meomeo888' ->> commander
commander

[1] "Meomeo888"

In [51]:
cat('Hello\n', 'World')

Hello
 World

In [52]:
ls()

[1] "cat"              "clan"             "commander"        "country"         
 [5] "gender"           "genders"          "level"            "mat"             
 [9] "name"             "player"           "stringAsFactor"   "stringAsFactors" 
[13] "stringsAsFactors"

In [53]:
clan.VN = c('VN Champions', 'VIET NAM')

In [54]:
ls()

[1] "cat"              "clan"             "clan.VN"          "commander"       
 [5] "country"          "gender"           "genders"          "level"           
 [9] "mat"              "name"             "player"           "stringAsFactor"  
[13] "stringAsFactors"  "stringsAsFactors"

In [55]:
ls(all.names = TRUE)

[1] ".pbd_env"         "cat"              "clan"             "clan.VN"         
 [5] "commander"        "country"          "gender"           "genders"         
 [9] "level"            "mat"              "name"             "player"          
[13] "stringAsFactor"   "stringAsFactors"  "stringsAsFactors"

In [56]:
ls(pattern = 'gen')

[1] "gender"  "genders"

In [57]:
rm(clan)

In [63]:
help(rm)

In [64]:
7 %% 3

[1] 1

In [65]:
7 %/% 3

[1] 2

In [76]:
c(TRUE, TRUE, FALSE) && c(FALSE, FALSE, FALSE)

[1] FALSE

In [77]:
1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [78]:
n <- 5
1:n

[1] 1 2 3 4 5

In [79]:
5 %in% c(5, 3, 2)

[1] TRUE

In [80]:
'Pikachu' %in% c('Pi', 'Po')

[1] FALSE

In [81]:
matrix(c(1,2,3,4), nrow = 2, ncol = 2) %*% matrix(c(1,0,0,1), nrow = 2, ncol = 2) 

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [85]:
print(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))

     [,1] [,2]
[1,]    1    2
[2,]    3    4


In [87]:
day <- 'Monday'
res <- c('Saturday', 'Sunday')

if(day %in% res) {
    print('let go hunt')
} else {
    print('Not again')
}

[1] "Not again"


In [90]:
i <- 10
switch(i < 10, 'good', 'bad')

In [91]:
switch('name', 'name' = 'VN Pikachu', 'clan' = 'VN Champions')

[1] "VN Pikachu"

In [93]:
help(switch)

In [94]:
factorial <- function(n) {
    if(n == 0)
        return (1)
    return (n * factorial(n - 1))
}

factorial(3)

[1] 6

In [97]:
for(value in 1:10) {
    if(value %% 3 == 0)
        next
    print(value)
}

[1] 1
[1] 2
[1] 4
[1] 5
[1] 7
[1] 8
[1] 10


In [100]:
mean(1:10)

[1] 5.5

In [102]:
avg(1:10)

ERROR: Error in avg(1:10): could not find function "avg"


In [104]:
help(seq)

In [105]:
seq(0, 1, length.out = 11)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

In [106]:
name <- 'VN Pikachu'
name

[1] "VN Pikachu"

In [109]:
substring(name, 2, 5)

[1] "N Pi"

In [119]:
paste('hello', 'world', sep = ', ')

[1] "hello, world"

In [127]:
help(paste)

In [122]:
help(substring)

In [123]:
help(strsplit)

In [124]:
help(toString)

In [126]:
nchar(c('VN pikachu', 'Tank Cao'))

[1] 10  8

In [128]:
help(rep)

In [134]:
format(c(1.32, 35.21, 343), nsmall = 5, width = 20, justify = 'l', digits = 10)

[1] "             1.32000" "            35.21000" "           343.00000"

In [135]:
help(as.character)

In [136]:
1:9

[1] 1 2 3 4 5 6 7 8 9

In [137]:
9:-2

[1]  9  8  7  6  5  4  3  2  1  0 -1 -2

In [138]:
seq(1, 10)

[1]  1  2  3  4  5  6  7  8  9 10

In [139]:
seq(1, 10, 2)

[1] 1 3 5 7 9

In [142]:
seq(along.with = c(1,2,3))

[1] 1 2 3

In [143]:
day = c("Sun","Mon","Tue","Wed","Thurs","Fri","Sat")
day[1]

[1] "Sun"

In [151]:
values <- c(1,2,3)
values[values %% 2 == 1]

[1] 1 3

In [152]:
day[c(1,2,1)]

[1] "Sun" "Mon" "Sun"

In [153]:
c(1,1) + c(1,2,3,4)

[1] 2 3 4 5

In [155]:
help(c)

In [156]:
help(as.vector)

In [157]:
c(name = 'VN Pikachu', clan = 'VN Champions')

name           clan 
  "VN Pikachu" "VN Champions"

In [158]:
help(sort)

In [159]:
unlist(list('VN Pikachu', 'VN Champions'))

[1] "VN Pikachu"   "VN Champions"

In [173]:
res <- pairlist(c('VN Champions', '03-rus', 'King Allool'), c('Meomeo888', 'SV2912', 'xXx-Hadi-xXx'))
print(res)

[[1]]
[1] "VN Champions" "03-rus"       "King Allool" 

[[2]]
[1] "Meomeo888"    "SV2912"       "xXx-Hadi-xXx"



In [182]:
filter <- array(1:8, dim = c(2,2,2), dimnames = list(c('r1', 'r2'), c('c1', 'c2'), c('d1', 'd2')))
print(filter)

, , d1

   c1 c2
r1  1  3
r2  2  4

, , d2

   c1 c2
r1  5  7
r2  6  8



In [178]:
filter[,,1]

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [179]:
filter[,,2]

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [185]:
filter[,,'d2']

c1 c2
r1 5  7 
r2 6  8

In [188]:
help(factor)

In [189]:
help(data.frame)

In [190]:
help(matrix)

In [192]:

# Create data for the graph.
x <- c(21, 62, 10, 53)
labels <- c("London", "New York", "Singapore", "Mumbai")

# Give the chart file a name.
png(file = "city.png")

# Plot the chart.
pie(x,labels)

In [193]:
emp.data <- data.frame(
    emp_id = c (1:5), 
    emp_name = c("Rick","Dan","Michelle","Ryan","Gary"),
    salary = c(623.3,515.2,611.0,729.0,843.25),
    start_date = as.Date(c("2012-01-01", "2013-09-23", "2014-11-15", "2014-05-11", "2015-03-27")),
    stringsAsFactors = FALSE
)
emp.data

emp_id emp_name salary start_date
1 1      Rick     623.30 2012-01-01
2 2      Dan      515.20 2013-09-23
3 3      Michelle 611.00 2014-11-15
4 4      Ryan     729.00 2014-05-11
5 5      Gary     843.25 2015-03-27

In [194]:
str(emp.data)

'data.frame':	5 obs. of  4 variables:
 $ emp_id    : int  1 2 3 4 5
 $ emp_name  : chr  "Rick" "Dan" "Michelle" "Ryan" ...
 $ salary    : num  623 515 611 729 843
 $ start_date: Date, format: "2012-01-01" "2013-09-23" ...


In [195]:
summary(emp.data)

     emp_id    emp_name             salary        start_date        
 Min.   :1   Length:5           Min.   :515.2   Min.   :2012-01-01  
 1st Qu.:2   Class :character   1st Qu.:611.0   1st Qu.:2013-09-23  
 Median :3   Mode  :character   Median :623.3   Median :2014-05-11  
 Mean   :3                      Mean   :664.4   Mean   :2014-01-14  
 3rd Qu.:4                      3rd Qu.:729.0   3rd Qu.:2014-11-15  
 Max.   :5                      Max.   :843.2   Max.   :2015-03-27  

In [198]:
emp.newdata <- 	data.frame(
   emp_id = c (6:8), 
   emp_name = c("Rasmi","Pranab","Tusar"),
   salary = c(578.0,722.5,632.8), 
   start_date = as.Date(c("2013-05-21","2013-07-30","2014-06-17")),
  
   stringsAsFactors = FALSE
)

In [199]:
rbind(emp.data, emp.newdata)

emp_id emp_name salary start_date
1 1      Rick     623.30 2012-01-01
2 2      Dan      515.20 2013-09-23
3 3      Michelle 611.00 2014-11-15
4 4      Ryan     729.00 2014-05-11
5 5      Gary     843.25 2015-03-27
6 6      Rasmi    578.00 2013-05-21
7 7      Pranab   722.50 2013-07-30
8 8      Tusar    632.80 2014-06-17

In [200]:
args(max)

function (..., na.rm = FALSE) 
NULL

In [201]:
x <- 5
log10(x^10)

[1] 6.9897

In [202]:
log(exp(5))

[1] 5

In [203]:
args(list)

function (...) 
NULL

In [204]:
args(max)

function (..., na.rm = FALSE) 
NULL

In [1]:
install.packages('dslabs')

also installing the dependencies 'ps', 'processx', 'callr', 'prettyunits', 'backports', 'desc', 'pkgbuild', 'rprojroot', 'rstudioapi', 'pkgload', 'praise', 'lattice', 'colorspace', 'assertthat', 'utf8', 'testthat', 'nlme', 'Matrix', 'farver', 'labeling', 'lifecycle', 'munsell', 'R6', 'RColorBrewer', 'viridisLite', 'cli', 'ellipsis', 'fansi', 'magrittr', 'pillar', 'pkgconfig', 'vctrs', 'glue', 'gtable', 'isoband', 'MASS', 'mgcv', 'rlang', 'scales', 'tibble', 'withr', 'ggplot2'




  There is a binary version available but the source version is later:
      binary source needs_compilation
callr  3.5.0  3.5.1             FALSE

package 'ps' successfully unpacked and MD5 sums checked
package 'processx' successfully unpacked and MD5 sums checked
package 'prettyunits' successfully unpacked and MD5 sums checked
package 'backports' successfully unpacked and MD5 sums checked
package 'desc' successfully unpacked and MD5 sums checked
package 'pkgbuild' successfully unpacked and MD5 sums checked
package 'rprojroot' successfully unpacked and MD5 sums checked
package 'rstudioapi' successfully unpacked and MD5 sums checked
package 'pkgload' successfully unpacked and MD5 sums checked
package 'praise' successfully unpacked and MD5 sums checked
package 'lattice' successfully unpacked and MD5 sums checked
package 'colorspace' successfully unpacked and MD5 sums checked
package 'assertthat' successfully unpacked and MD5 sums checked
package 'utf8' successfully unpacked and MD5 sum

installing the source package 'callr'



In [5]:
library(dslabs)
data(movielens)

movielens

movieId
1        31   
2      1029   
3      1061   
4      1129   
5      1172   
6      1263   
7      1287   
8      1293   
9      1339   
10     1343   
11     1371   
12     1405   
13     1953   
14     2105   
15     2150   
16     2193   
17     2294   
18     2455   
19     2968   
20     3671   
21       10   
22       17   
23       39   
24       47   
25       50   
26       52   
27       62   
28      110   
29      144   
30      150   
...    ...    
99975  4034   
99976  4306   
99977  4308   
99978  4880   
99979  4886   
99980  4896   
99981  4963   
99982  4973   
99983  4993   
99984  4995   
99985  5010   
99986  5218   
99987  5299   
99988  5349   
99989  5377   
99990  5445   
99991  5464   
99992  5669   
99993  5816   
99994  5902   
99995  5952   
99996  5989   
99997  5991   
99998  5995   
99999  6212   
100000 6268   
100001 6269   
100002 6365   
100003 6385   
100004 6565   
       title                                                                                  
1      Dangerous Minds                                                                        
2      Dumbo                                                                                  
3      Sleepers                                                                               
4      Escape from New York                                                                   
5      Cinema Paradiso (Nuovo cinema Paradiso)                                                
6      Deer Hunter, The                                                                       
7      Ben-Hur                                                                                
8      Gandhi                                                                                 
9      Dracula (Bram Stoker's Dracula)                                                        
10     Cape Fear                                                                              
11     Star Trek: The Motion Picture                                                          
12     Beavis and Butt-Head Do America                                                        
13     French Connection, The                                                                 
14     Tron                                                                                   
15     Gods Must Be Crazy, The                                                                
16     Willow                                                                                 
17     Antz                                                                                   
18     Fly, The                                                                               
19     Time Bandits                                                                           
20     Blazing Saddles                                                                        
21     GoldenEye                                                                              
22     Sense and Sensibility                                                                  
23     Clueless                                                                               
24     Seven (a.k.a. Se7en)                                                                   
25     Usual Suspects, The                                                                    
26     Mighty Aphrodite                                                                       
27     Mr. Holland's Opus                                                                     
28     Braveheart                                                                             
29     Brothers McMullen, The                                                                 
30     Apollo 13                                                                              
...    ...                                                                                    
99975  Traffic                       

In [6]:
str(movielens)

'data.frame':	100004 obs. of  7 variables:
 $ movieId  : int  31 1029 1061 1129 1172 1263 1287 1293 1339 1343 ...
 $ title    : chr  "Dangerous Minds" "Dumbo" "Sleepers" "Escape from New York" ...
 $ year     : int  1995 1941 1996 1981 1989 1978 1959 1982 1992 1991 ...
 $ genres   : Factor w/ 901 levels "(no genres listed)",..: 762 510 899 120 762 836 81 762 844 899 ...
 $ userId   : int  1 1 1 1 1 1 1 1 1 1 ...
 $ rating   : num  2.5 3 3 2 4 2 2 2 3.5 2 ...
 $ timestamp: int  1260759144 1260759179 1260759182 1260759185 1260759205 1260759151 1260759187 1260759148 1260759125 1260759131 ...


In [10]:
nlevels(movielens$genres)

[1] 901

In [11]:
values <- 3:1
sort(values)

[1] 1 2 3

In [12]:
values

[1] 3 2 1

In [4]:
name <- c("Mandi", "Amy", "Nicole", "Olivia")
distance <- c(0.8, 3.1, 2.8, 4.0)
time <- c(10, 30, 40, 50)
time = time / 60
names(time) <- name
time

Mandi       Amy    Nicole    Olivia 
0.1666667 0.5000000 0.6666667 0.8333333

In [3]:
v <- distance / time
names(v) <- name
v

Mandi    Amy Nicole Olivia 
   4.8    6.2    4.2    4.8

In [6]:
?ifelse

In [7]:
levels

function (x) 
UseMethod("levels")
<bytecode: 0x00000000418b7b40>
<environment: namespace:base>

In [10]:
players <- c(31, 32, 33)
for (i in seq(along.with = players)) {
    print(i)
}

[1] 1
[1] 2
[1] 3
