<img src = './subsetting.png'/>

In [21]:
library(tidyverse)

# Simplifying vs. Preserving Subsetting

* **Simplifying**: Return the simplest data structure that can represent the output
* **Preserving**: The output has the same data sructure as the input (when you you `drop = FASLE`,it's preserving)

In [3]:
# atomic vector
# preserving is the same as simplifying
letters[[2]]

letters[2]

[1] "b"

[1] "b"

In [10]:
# list
# preserving return a list
# simplifying return a vector

player <- list(name = 'VN pikachu', level= 31)

print(player[['name']]) # simplifying, return a vector

[1] "VN pikachu"


In [8]:
print(player['name'])   # preserving, return a list

$name
[1] "VN pikachu"



In [18]:
mat <- matrix(1:12, nrow = 3)

mat

mat[, 2]             # simplifying, return a vector

mat[, 2, drop = F]   # preserving, return a matrix of 1 column

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 4 5 6

[,1]
[1,] 4   
[2,] 5   
[3,] 6

In [14]:
iris[, 'Species', drop = F]  # preserving, return a data.frame
iris[, 'Species', drop = T]  # simplying, return a factor

Species  
1   setosa   
2   setosa   
3   setosa   
4   setosa   
5   setosa   
6   setosa   
7   setosa   
8   setosa   
9   setosa   
10  setosa   
11  setosa   
12  setosa   
13  setosa   
14  setosa   
15  setosa   
16  setosa   
17  setosa   
18  setosa   
19  setosa   
20  setosa   
21  setosa   
22  setosa   
23  setosa   
24  setosa   
25  setosa   
26  setosa   
27  setosa   
28  setosa   
29  setosa   
30  setosa   
... ...      
121 virginica
122 virginica
123 virginica
124 virginica
125 virginica
126 virginica
127 virginica
128 virginica
129 virginica
130 virginica
131 virginica
132 virginica
133 virginica
134 virginica
135 virginica
136 virginica
137 virginica
138 virginica
139 virginica
140 virginica
141 virginica
142 virginica
143 virginica
144 virginica
145 virginica
146 virginica
147 virginica
148 virginica
149 virginica
150 virginica

[1] setosa     setosa     setosa     setosa     setosa     setosa    
  [7] setosa     setosa     setosa     setosa     setosa     setosa    
 [13] setosa     setosa     setosa     setosa     setosa     setosa    
 [19] setosa     setosa     setosa     setosa     setosa     setosa    
 [25] setosa     setosa     setosa     setosa     setosa     setosa    
 [31] setosa     setosa     setosa     setosa     setosa     setosa    
 [37] setosa     setosa     setosa     setosa     setosa     setosa    
 [43] setosa     setosa     setosa     setosa     setosa     setosa    
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica 
[103] virginica  virginica  virginica  virginica  virginica  virginica 
[109] virginica  virginica  virginica  virginica  virginica  virginica 
[115] virginica  virginica  virginica  virginica  virginica  virginica 
[121] virginica  virginica  virginica  virginica  virginica  virginica 
[127] virginica  virginica  virginica  virginica  virginica  virginica 
[133] virginica  virginica  virginica  virginica  virginica  virginica 
[139] virginica  virginica  virginica  virginica  virginica  virginica 
[145] virginica  virginica  virginica  virginica  virginica  virginica 
Levels: setosa versicolor virginica

# Data Frame subsetting

Data Frame posseses characteristics of both:
* List
* Matrices

Subset with a single vector, behave like list

In [26]:
# if you give a single vector to subset a data frame then it will behave like list
iris[c(1, 2)]  %>% str()

'data.frame':	150 obs. of  2 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...


Subset with 2 vectors, behave like matrices

In [27]:
# If you give 2 vectors to subset a data frame, then it will behave like matrices
iris[, c(1, 2)]  %>% str()

'data.frame':	150 obs. of  2 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...


# Subsetting operator

* `$` does partial matching (`x$y` is equivalent to `x[['y', exact = F]`)`
* `[[` does exact matching  (`x[['y']` is equivalent to `x[['y', exact = T]`)

In [29]:
player <- list(name = 'VN Pikachu')

In [31]:
player$na

[1] "VN Pikachu"

In [32]:
player[['na']]

NULL

# Array and Matrices

 both matrices and arrays are just vectors with special attributes, you can subset them with a single vector, as if they were a 1D vector. Note that arrays in R are stored in column-major order:

In [1]:
values <- matrix(1:12, nrow = 3)

values

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [2]:
values[c(5, 9)]

[1] 5 9

# Missing and out-of-boundary indicies

`row[[col]]`|Zero-length	|OOB (int)	|OOB (chr)	|Missing
------------|---------------|-----------|-----------|-------
Atomic	    |Error	        |Error	    |Error	    |Error
List	    |Error	        |Error	    |NULL	    |NULL
NULL	    |NULL	        |NULL	    |NULL	    |NULL

In [1]:
# atomic vector
values <- 1:5

# zero length
values[[integer(0)]]

# out of bound integer indices
values[[6]]

# missing
values[[]]


ERROR: Error in values[[integer(0)]]: attempt to select less than one element in get1index


# Subsetting with `purrr::pluck` and `purrr::chuck`

Read the document

# Subsetting with nothing

Subsetting with nothing can be useful with assignment because it preserves the structure of the original object. Compare the following two expressions. In the first, `mtcars` remains a data frame because you are only changing the contents of `mtcars`, not `mtcars` itself. In the second, `mtcars` becomes a list because you are changing the object it is bound to.

In [1]:
mtcars[] <- lapply(mtcars, as.integer)
is.data.frame(mtcars)
#> [1] TRUE

mtcars <- lapply(mtcars, as.integer)
is.data.frame(mtcars)

[1] TRUE

[1] FALSE

In [2]:
# change all the values of a matrix to 0
values <- matrix(1:12, nrow = 3)

values[] <- 0   # we can't do values <- 0

values

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0