In [2]:
import numpy as np

# Real Numbers

## np.add, np.subtract, np.multiply, np.divide, np.mod, np.power, np.exp, np.log, np.log2, np.log10, np.log1p, np.true_divide, np.floor_divide

In [4]:
x1 = np.array([1,2])
x2 = np.array([3,4])
np.add(x1, x2, out = x1) #adding inplace without creating a copy
x1

array([4, 6])

In [3]:
np.add([1,2], [3,4])

array([4, 6])

In [5]:
np.subtract([[1,2], [3,4]], 1)

array([[0, 1],
       [2, 3]])

In [6]:
np.multiply(2, [1,2])

array([2, 4])

In [7]:
np.divide([2, 6], 2)

array([1., 3.])

In [8]:
np.power([1,2], [3,4])

array([ 1, 16], dtype=int32)

In [9]:
np.exp(3322)

inf

In [14]:
np.reciprocal([1/2, 1/3, 1/4])

array([2., 3., 4.])

## advanced

In [4]:
dir(np.add) #share functions for np.substract, np.multiply, np.logical_and, ....

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

In [6]:
arr = np.arange(8)
np.add.reduceat(arr,[0,4, 1,5, 2,6, 3,7])


array([ 6,  4, 10,  5, 14,  6, 18,  7], dtype=int32)

In [14]:
np.logical_xor.reduce([True, True, False]) #True ^ True ^ False

False

# Complex Numbers

In [15]:
nums = np.array([1 + 2j, 5 + 6j, 8 + 1j])
nums

array([1.+2.j, 5.+6.j, 8.+1.j])

In [16]:
np.real(nums)

array([1., 5., 8.])

In [17]:
np.imag(nums)

array([2., 6., 1.])

In [19]:
np.conjugate(nums)

array([1.-2.j, 5.-6.j, 8.-1.j])

In [20]:
np.angle(nums)

array([1.10714872, 0.87605805, 0.12435499])

# np.diff

return the difference between 2 consecutive numbers

In [3]:
a = np.array([1, 2, 4, 7, 11])
np.diff(a)

array([1, 2, 3, 4])

# np.sign

In [4]:
np.sign([-2, 0, 5])

array([-1,  0,  1])