In [1]:
import numpy as np

# np.empty(shape)

let's create an ndarray of shape (3,2), dtype = 'complex'

In [4]:
data = np.empty((3,2), dtype = 'complex')
data

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

# np.empty_like(arr)

In [5]:
np.empty_like([[1,2], [3,4]])

array([[0, 0],
       [0, 0]])

# np.zeros(shape)

Create an ndarray filled with 0 of shape (m, n), datatype = 'float'

In [9]:
vector = np.zeros((3,3), dtype = 'float')
vector

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# np.zeros_like(shape)

Create an array filled with zeros having the same shape as the reference array

In [10]:
reference_array = [[2,3],[4,5],[6,7]]
reference_array

[[2, 3], [4, 5], [6, 7]]

In [11]:
np.zeros_like(reference_array)

array([[0, 0],
       [0, 0],
       [0, 0]])

# np.ones(shape)

In [12]:
np.ones((3,3), dtype = 'complex')

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

# np.ones_like(array)

In [13]:
np.ones_like(reference_array)

array([[1, 1],
       [1, 1],
       [1, 1]])

# np.identity

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# np.eye(n)

```python
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
-----------
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.
```
shape (N, M)
k: index of the diagonal

In [9]:
#default
np.eye(3) #identity matrix (3x3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3, k = -1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [8]:
np.eye(3, k = 1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.eye(N = 3, M = 4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np.diagonal

Create an ndarray with the diagnonal = diagonal_array

In [16]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [2]:
#matrix with 1-th diag = [1,2,3]
np.diag([1,2,3], k = 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

get the diagonal of a matrix 

In [20]:
target = np.arange(25).reshape((5,5))
target

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
np.diag(target)

array([ 0,  6, 12, 18, 24])

get the k<sup>th</sup> upper diagonal

In [22]:
np.diag(target, k = 2)

array([ 2,  8, 14])

get the k<sup>th</sup> lower diagonal

In [23]:
np.diag(target, k = -1)

array([ 5, 11, 17, 23])

# np.full(shape,fill_value)

Create an ndarray with given shape, filled with a value

In [25]:
np.full((3,3), -1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

# np.full_like()

In [6]:
np.full_like([[1,2], [3,4]], -1)

array([[-1, -1],
       [-1, -1]])

# np.triu, np.trl

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
# Return a copy of a matrix with the elements below the `k`-th diagonal zeroed.
np.triu(arr, k = 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [12]:
#Return a copy of a matrix with the elements above the `k`-th diagonal zeroed.
np.tril(arr, k = 0)

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

# np.triu_indices, np.tril_indices

In [6]:
help(np.triu_indices)

Help on function triu_indices in module numpy:

triu_indices(n, k=0, m=None)
    Return the indices for the upper-triangle of an (n, m) array.
    
    Parameters
    ----------
    n : int
        The size of the arrays for which the returned indices will
        be valid.
    k : int, optional
        Diagonal offset (see `triu` for details).
    m : int, optional
        .. versionadded:: 1.9.0
    
        The column dimension of the arrays for which the returned
        arrays will be valid.
        By default `m` is taken equal to `n`.
    
    
    Returns
    -------
    inds : tuple, shape(2) of ndarrays, shape(`n`)
        The indices for the triangle. The returned tuple contains two arrays,
        each with the indices along one dimension of the array.  Can be used
        to slice a ndarray of shape(`n`, `n`).
    
    See also
    --------
    tril_indices : similar function, for lower-triangular.
    mask_indices : generic function accepting an arbitrary mask function.
 

In [7]:
# lower triangle indices of a 5 x 4 matrix (including the main diagonal, modify the k parameter)
np.tril_indices(n=5,m=4,k=0)



(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3]))

# Randomness

In [27]:
from numpy import random

In [29]:
random.random((2,2))

array([[0.56656161, 0.57497282],
       [0.39147145, 0.17040212]])

# np.arange

In [31]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

# np.linspace

In [34]:
np.linspace(1,10, 10, dtype = 'int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# np.fromfunction

In [13]:
np.info(np.fromfunction)

 fromfunction(function, shape, **kwargs)

Construct an array by executing a function over each coordinate.

The resulting array therefore has a value ``fn(x, y, z)`` at
coordinate ``(x, y, z)``.

Parameters
----------
function : callable
    The function is called with N parameters, where N is the rank of
    `shape`.  Each parameter represents the coordinates of the array
    varying along a specific axis.  For example, if `shape`
    were ``(2, 2)``, then the parameters would be
    ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
shape : (N,) tuple of ints
    Shape of the output array, which also determines the shape of
    the coordinate arrays passed to `function`.
dtype : data-type, optional
    Data-type of the coordinate arrays passed to `function`.
    By default, `dtype` is float.

Returns
-------
fromfunction : any
    The result of the call to `function` is passed back directly.
    Therefore the shape of `fromfunction` is completely determined by
    `function`

create an array (3x 3) of complex type, index (i,j) has value i * j

In [15]:
np.fromfunction(lambda i, j: i * j, shape = (3,3), dtype = np.complex)

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 2.+0.j],
       [0.+0.j, 2.+0.j, 4.+0.j]])