In [2]:
import numpy as np

# Shape changing

## reshape

In [2]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
arr.reshape((2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
#reshape return a view
a = np.array([1,2,3,4])
b = a.reshape((2,2))
b[0,0] = -1
a

array([-1,  2,  3,  4])

In [3]:
#reshape using F order: first, create an array with given reshape, then fill value to that array in F oder 
np.arange(15).reshape((5,3), order = 'F')

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## flat

return a 1D iterator over the array

In [6]:
ndarray.flat.base

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
ndarray = np.arange(9).reshape((3,3))

In [4]:
ndarray.flat.base

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
for row in arr.flat:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [2]:
#access value of 2D array as 1D
arr = np.array([[1,2,3], [4,5,6]])
arr.flat[3]

4

In [3]:
#modify value
arr.flat[[0, 5]] = -1
arr

array([[-1,  2,  3],
       [ 4,  5, -1]])

# flatten

Returns a copy of the array collapsed into one dimension

In [5]:
ndarray.flatten().base is None

True

In [4]:
arr

array([[-1,  2,  3],
       [ 4,  5, -1]])

In [5]:
arr.flatten()

array([-1,  2,  3,  4,  5, -1])

In [6]:
arr.flatten(order = 'F')

array([-1,  4,  2,  5,  3, -1])

## ravel()

Returns a contiguous flattened array

In [7]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr.ravel(order = 'F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

Understanding **`ndarray.ravel()`**: return a flatten **view** of ndarray

In [9]:
array = np.arange(9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#get the view of array, flatten
view = array.ravel()
view

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
#when we change the value of view, values in array will also be changed
view[2] = -1
view

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8])

In [12]:
array

array([[ 0,  1, -1],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [13]:
#order = 'F'
array.ravel(order = 'F')

array([ 0,  3,  6,  1,  4,  7, -1,  5,  8])

# Transpose Operations

## ndarray.T

In [9]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## np.swapaxes(arr, axis1, axis2)

let's transpose by `using np.swapaxes`

In [11]:
np.swapaxes(arr, 0, 1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Changing Dimensions

## np.expand_dims(arr, axis)

In [16]:
data = np.array([1,2,3])
np.expand_dims(data, 0) #equivalent: data[np.newaxis, :]

(array([[1, 2, 3]]), array([[1, 2, 3]]))

In [17]:
data[np.newaxis,:]

array([[1, 2, 3]])

In [15]:
np.expand_dims(data, 1) #equivalent: data[:, np.newaxis]

array([[1],
       [2],
       [3]])

insert a new axis within a 2-D array, change shape from (3,4) to (3,1,4)

In [6]:
arr = np.arange(12).reshape((3,4))
arr.shape

(3, 4)

In [9]:
np.expand_dims(arr, axis = 1).shape

(3, 1, 4)

## np.squeeze(arr, axis)

inverse **`np.expand_dims`**

In [8]:
data = np.array([[1,2,3]])
data

array([[1, 2, 3]])

In [9]:
np.squeeze(data, axis = 0)

array([1, 2, 3])

In [10]:
data.T

array([[1],
       [2],
       [3]])

In [11]:
np.squeeze(data.T, axis = 1)

array([1, 2, 3])

# Joining Arrays

## np.concatenate((arr1, arr2, ...), axis)

In [16]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [17]:
arr2 = np.array([[4,5], [6, 7]])
arr2

array([[4, 5],
       [6, 7]])

In [18]:
arr3 = np.array([[8, 9], [10, 11]])
arr3

array([[ 8,  9],
       [10, 11]])

In [19]:
np.concatenate((arr1, arr2, arr3), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [20]:
np.concatenate((arr1, arr2, arr3), axis = 1)

array([[ 1,  2,  4,  5,  8,  9],
       [ 3,  4,  6,  7, 10, 11]])

## np.hstack(tuple_of_arrays)

In [20]:
np.hstack(((1,2,3), (3,4,5)))

array([1, 2, 3, 3, 4, 5])

In [21]:
#equivalent np.concatenate(tuple, axis = 1)
np.hstack((arr1, arr2, arr3))

array([[ 1,  2,  4,  5,  8,  9],
       [ 3,  4,  6,  7, 10, 11]])

## np.vstack(tuple_of_arrays)

In [21]:
np.vstack(((1,2,3), (4,5,6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#equivalent: np.concatenate(tuple, axis = 0)
np.vstack((arr1, arr2, arr3))

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# np.dstack

In [11]:
#stack depth-wise (along the third dimension)
#let's create a rgb image
red_channel = np.ones((10,10))
green_channel = np.zeros((10,10))
blue_channel = np.ones((10,10))
img = np.dstack((red_channel, green_channel, blue_channel))
img.shape

(10, 10, 3)

## np.stack(tuple_of_arrays, axis)

Joins a sequence of arrays along a new axis

### np.stack((arr1, arr2, ...), axis = 0)

return `np.array([arr1, arr2, arr3, ...])`

In [62]:
arr1 = [1,2]
arr2 = [3,4]

In [63]:
np.stack((arr1, arr2), axis = 0)

array([[1, 2],
       [3, 4]])

In [64]:
np.stack((arr1, arr2), axis = 1)

array([[1, 3],
       [2, 4]])

**`np.column_stack`**

In [2]:
np.column_stack(([1,2], [3,4]))

array([[1, 3],
       [2, 4]])

**`np.row_stack`**

In [3]:
np.row_stack(([1,2], [3,4]))

array([[1, 2],
       [3, 4]])

## np.r_[arr1, arr2, arr3, ....]

treat each array as row, stack vertically

In [30]:
arr1 = np.array([[1,2], [3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [31]:
arr2 = np.array([[5,6], [7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [32]:
np.r_[arr1, arr2]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## np.c_[arr1, arr2, ...]

treat each array as column, stack horizontally

In [33]:
np.c_[arr1, arr2]

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Splitting Arrays

## np.split

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

split into three chunks:

In [35]:
#this is not possible because np.split only allows equal chunks
#np.split(arr, 3)

In [36]:
#use np.array_split instead
np.array_split(arr, 3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

split at marked points:

In [37]:
np.split(arr, [2, 7])

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8, 9])]

## np.array_split

In [13]:
#1d split
a = np.array([1,2,3,4,5])
np.array_split(a, 2)

[array([1, 2, 3]), array([4, 5])]

In [16]:
#2d split
b = np.arange(25).reshape((5,-1))
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
#2d split(horizontally) into 3 chunks (does not raise errow if #colunns is not divible by 3)
np.array_split(b, 3, axis = 1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]), array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]]), array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [18]:
#2d split(vertically)
np.array_split(b, 3, axis = 0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24]])]

## np.hsplit

<b style = 'color:red'>inverse of <code>np.hstack</code></b><br>
split an array into subarrays horizontally (column-wise)

In [38]:
my_arr = np.array([[1,2],[3,4]])
my_arr

array([[1, 2],
       [3, 4]])

split into 2 columns

In [39]:
for v in np.hsplit(my_arr, 2):
    print(v)
    print('------')

[[1]
 [3]]
------
[[2]
 [4]]
------


<pre>
|1 2| ---> |1|   |2|
|3 4| ---> |3|   |4|
</pre>

## np.vsplit

<b style = 'color:red'>inverse of <code>np.vstack</code></b><br>
split an array into subarrays vertically(row-wise)

In [40]:
my_arr = np.arange(12).reshape((6,2))
my_arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [41]:
for v in np.vsplit(my_arr, 3):
    print(v)
    print('-------')

[[0 1]
 [2 3]]
-------
[[4 5]
 [6 7]]
-------
[[ 8  9]
 [10 11]]
-------


## np.dsplit

inverse of **`np.dstack`**

extract r, g, b channel from an image:

In [12]:
image = np.random.randint(0,256,(10,10,3))
r,g,b = np.dsplit(image, 3)

In [13]:
r.shape, g.shape, b.shape

((10, 10, 1), (10, 10, 1), (10, 10, 1))

# Adding/removing elements

## np.append(arr, value, axis = None)

return a new array 

In [23]:
ndarray = np.array([1,2,3], dtype = np.int)
ndarray

array([1, 2, 3])

In [24]:
#append 1 element
np.append(ndarray, 4)

array([1, 2, 3, 4])

In [25]:
#append multiple elements
np.append(ndarray, [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [27]:
#values keyword acept array-like input
#If `axis` is not specified, `values` can be any shape and will beflattened before use.
np.append(ndarray, [[4,5], [9,10]])

array([ 1,  2,  3,  4,  5,  9, 10])

In [32]:
#When `axis` is specified, `values` must have the correct shape.
np.append([[1,2], [3,4]], [[5, 6]], axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## np.delete(arr, obj, axis)

Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
`arr[obj]`.

In [44]:
arr_1D = np.arange(10)
arr_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.delete(arr_1D, [2,4,5])

array([0, 1, 3, 6, 7, 8, 9])

In [36]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

let's remove the 1-th and the 3-th column (0-based)

In [37]:
np.delete(arr, [1, 3], axis = 1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

let's remove the 1-th row

In [38]:
np.delete(arr, 1, axis = 0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

delete every 2-th column: **`np.s_`**

In [39]:
np.delete(arr, np.s_[::2], axis = 1)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

## np.unique

`np.unique(
    ar,
    return_index=False,
    return_inverse=False,
    return_counts=False,
    axis=None,
)`

In [49]:
nums = np.random.randint(2,5,10)
nums

array([4, 2, 2, 3, 4, 3, 4, 2, 4, 2])

In [50]:
np.unique(nums)

array([2, 3, 4])

In [51]:
#return_index = True
#arr[return_index] = np.unique(arr)
np.unique(nums, return_index = True)

(array([2, 3, 4]), array([1, 3, 0], dtype=int64))

In [52]:
#arr[return_inverse] = arr
np.unique(nums, return_inverse = True)

(array([2, 3, 4]), array([2, 0, 0, 1, 2, 1, 2, 0, 2, 0], dtype=int64))

In [53]:
np.unique(nums, return_counts = True)

(array([2, 3, 4]), array([4, 2, 4], dtype=int64))

## np.resize(arr, new_shape)

Return a new array with the specified shape.

If the new array is larger than the original array, then the new
array is filled with repeated copies of `a`.  Note that this behavior
is different from `a.resize(new_shape)` which fills with zeros instead
of repeated copies of `a`.


In [54]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
np.resize(arr, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.resize(arr, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

## numpy.insert(arr, obj, values, axis)

<b style = 'color:red'>inverse of <code>numpy.delete</code></b>

In [33]:
#insert into a 1D array
np.insert([0,1,2,3], [1, 3], [-1,-2])

array([ 0, -1,  1,  2, -2,  3])

In [34]:
#insert multiple values at the same position
np.insert([0,1,2,3], [1,1], [-1,-1])

array([ 0, -1, -1,  1,  2,  3])

In [57]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

insert into the 1-th row array [-1,-1, -1]

In [58]:
np.insert(arr, 1, [-1,-1,-1], axis = 0)

array([[ 1,  2,  3],
       [-1, -1, -1],
       [ 4,  5,  6]])

# Repeat

In [59]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

## np.tile

In [60]:
np.tile(arr, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [61]:
np.tile(arr, (2,4))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

## np.repeat

<h1 style = 'color:red'>Final Notes</h1>

How to reshape an array? first, flatten it. then reshape it.
