In [1]:
import numpy as np

# np.any

In [3]:
arr = np.array([
    [True, False],
    [False, False],
    [True, True],
])

In [7]:
np.any(arr, axis = 1, keepdims=True)

array([[ True],
       [False],
       [ True]])

In [9]:
np.any(arr, axis = 0)

array([ True,  True])

In [11]:
np.any(arr)

True

# np.all

In [12]:
np.all(arr)

False

In [13]:
np.all(arr, axis = 1)

array([False, False,  True])

In [14]:
np.all(arr, axis = 0, keepdims = True)

array([[False, False]])

# ndarray.any

In [15]:
arr.any()

True

# ndarray.all

In [16]:
arr.all(0)

array([False, False])

# np.nonzero

In [2]:
np.info(np.nonzero)

 nonzero(a)

Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of `a`,
containing the indices of the non-zero elements in that
dimension. The values in `a` are always tested and returned in
row-major, C-style order. The corresponding non-zero
values can be obtained with::

    a[nonzero(a)]

To group the indices by element, rather than dimension, use::

    transpose(nonzero(a))

The result of this is always a 2-D array, with a row for
each non-zero element.

Parameters
----------
a : array_like
    Input array.

Returns
-------
tuple_of_arrays : tuple
    Indices of elements that are non-zero.

See Also
--------
flatnonzero :
    Return indices that are non-zero in the flattened version of the input
    array.
ndarray.nonzero :
    Equivalent ndarray method.
count_nonzero :
    Counts the number of non-zero elements in the input array.

Examples
--------
>>> x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
>>> x
array([[3, 0, 0],
 

In [5]:
#get indices of values that are not 0
np.nonzero([0,1,0,2,3])

(array([1, 3, 4], dtype=int64),)

In [4]:
a = np.array([-1,12,5,3])
#get indices of values > 4
np.nonzero(a > 4)

(array([1, 2], dtype=int64),)

# Checking Functions

```python
np.is_busday
np.isclose
np.iscomplex
np.iscomplexobj
np.isfinite
np.isfortran
np.isin
np.isinf
np.isnan
np.isnat
np.isneginf
np.isposinf
np.isreal
np.isrealobj
np.isscalar
np.issctype
np.issubclass_
np.issubdtype
np.issubsctype
```

In [14]:
#check for infinite(both positive and negative)
np.isinf([np.inf, -np.inf, 0])

array([ True,  True, False])

In [12]:
#check for positive infinite
np.isposinf([1, np.inf, 2])

array([False,  True, False])

In [9]:
#check for negative infinite
np.isneginf([-np.inf, np.inf, 0])

array([ True, False, False])

In [10]:
#check for finite
np.isfinite([np.inf, -np.inf, 0])

array([False, False,  True])

# Check for equibrium

```python
np.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
```

In [24]:
help(np.isclose)

Help on function isclose in module numpy:

isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns a boolean array where two arrays are element-wise equal within a
    tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    .. warning:: The default `atol` is not appropriate for comparing numbers
                 that are much smaller than one (see Notes).
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output array.
    
    Returns
    -------


In [26]:
#if equal_nan = True --> compare nan vs nan will return True
np.isclose([1, np.nan], [1 + 1e-8, np.nan], equal_nan = True)

array([ True,  True])

In [22]:
#check if 2 values are closed
f = lambda x:  x * x
df = lambda x: 2 * x

def es_df(x, eps = 1e-7):
    return (f(x + eps) - f(x - eps)) / (2 * eps)

xs = np.random.rand(100)
grad = df(xs)
es_grad = es_df(xs)

np.isclose(grad, es_grad)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# np.allclose

```python
np.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
```

In [20]:
np.allclose(grad, es_grad)

True

# Comparation

**`np.equal`**, **`np.greater`**, **`np.greater_equal`**, **`np.less`**, **`np.less_equal`**

In [27]:
np.equal([1,2], [1,2])

array([ True,  True])

In [29]:
np.less([1,5], [2,3])

array([ True, False])