In [5]:
 import numpy as np

# Same dim

In [6]:
a = np.full((3,3), 10)
b = np.eye(3)

In [8]:
a

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [9]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a + b

array([[11., 10., 10.],
       [10., 11., 10.],
       [10., 10., 11.]])

# Dim difference

In [10]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
b = np.full(3, 10)
b

array([10, 10, 10])

In [15]:
print(a.shape, b.shape)

(3, 3) (3,)


In [14]:
a + b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Extreme Case

In [16]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [19]:
b = a.reshape((3, 1))
b

array([[1],
       [2],
       [3]])

In [22]:
print(b.shape, a.shape)

(3, 1) (3,)


In [20]:
b * a

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])