Reference: <https://www.gormanalysis.com/blog/python-numpy-for-your-grandma-6-2-einsum/>

In [1]:
import numpy as np

In [27]:
a = np.arange(10)
b = np.arange(10)
x = np.arange(6).reshape((2, 3))
y = np.arange(6).reshape((3, 2))
z = y.copy()
t = np.arange(9).reshape((3,3))

# Sum the value of a vector

In [4]:
a.sum()

45

In [5]:
np.einsum('i->', a)

45

In [6]:
x.sum(0)

array([3, 5, 7])

In [7]:
np.einsum('ij->j', x)

array([3, 5, 7])

In [8]:
x.sum(1)

array([ 3, 12])

In [9]:
np.einsum('ij->i', x)

array([ 3, 12])

In [10]:
x.sum()

15

In [11]:
np.einsum('ij->', x)

15

# Element-wise multiplication

In [12]:
a * b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
np.einsum('i,i->i',a,b)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
y * z

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [15]:
np.einsum('ij,ij->ij', y, z)

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

# Inner product

In [16]:
a @ b

285

In [17]:
np.einsum('i,i->', a, b)

285

In [18]:
# matrix multiplication
x @ y

array([[10, 13],
       [28, 40]])

In [19]:
np.einsum('ij,jk->ik', x, y)

array([[10, 13],
       [28, 40]])

# Outer product

In [20]:
np.outer(a, b)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [21]:
np.einsum('i,j->ij', a, b)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

# Transpose

In [22]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [23]:
np.einsum('ij->ji', x)

array([[0, 3],
       [1, 4],
       [2, 5]])

# Main diagonal

In [29]:
t.diagonal()

array([0, 4, 8])

In [28]:
np.einsum('ii->i',t)

array([0, 4, 8])

# Trace

In [30]:
t.trace()

12

In [31]:
np.einsum('ii', t)

12

# Exercies

In [2]:
# get the diagonal of a dot product

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.dot(A, B).diagonal()

array([2.19083233, 1.87132434, 2.05618991, 1.9029752 , 2.42104492])

In [3]:
np.einsum('ij,ji->i', A, B)

array([2.19083233, 1.87132434, 2.05618991, 1.9029752 , 2.42104492])


```python
for i:
    for j:
        res[i] += A[i][j] * B[j][i]  # so we write the formula: 'ij,ji->i'
```
        