In [1]:
import numpy as np

# Slicing

# ...

In [3]:
ndarray = np.logspace(1, 3, 9).reshape((3,3))
ndarray

array([[  10.        ,   17.7827941 ,   31.6227766 ],
       [  56.23413252,  100.        ,  177.827941  ],
       [ 316.22776602,  562.34132519, 1000.        ]])

In [4]:
ndarray[:, 2]

array([  31.6227766,  177.827941 , 1000.       ])

In [6]:
ndarray[..., :2]

array([[ 10.        ,  17.7827941 ],
       [ 56.23413252, 100.        ],
       [316.22776602, 562.34132519]])

# Indexing

## Integer Indexing

In [3]:
ndarray_1d = np.array([6, 10, 20001], dtype = 'int')
ndarray_1d

array([    6,    10, 20001])

In [4]:
ndarray_1d[[1,1,0,2]]

array([   10,    10,     6, 20001])

In [7]:
#create a 2D array from values of 1D array
array_index = np.array([[2,2], [1,0]])
ndarray_1d[array_index]

array([[20001, 20001],
       [   10,     6]])

In [10]:
ndarray_2d = np.arange(9).reshape((3,-1))
ndarray_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
ndarray_2d[[0, 0, 0], [0, 1,2]]

array([0, 1, 2])

How this works? <br>
`ndarray_2d[[r0, r1, r2, ...], [c0, c2, c2, ...]]` will return `[a[r0, c0], a[r1, c1], a[r2, c2], ...]`

let's select values at the coners

In [14]:
rows = [[0, 0], [2,2]]
cols = [[0, 2], [0, 2]]
ndarray_2d[rows, cols]

array([[0, 2],
       [6, 8]])

how this works?<br>

```python
rows = [
    [r1, r2],
    [r3, r4]
]

cols = [
    [c1, c2],
    [c3, c4]
]

#return
[
    [a[r1, c1], a[r2, c2]],
    [a[r3, c3], a[r4, c4]]
]
```

<b style = 'color:red'>NOTE: Broadcasting</b>

In [3]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
r = [
    [0],
    [2]
]

c = [0,2]

a[r,c] #broadcast r --> [[0,0], [2,2]], c --> [[0,2], [0,2]]

array([[ 0,  2],
       [ 8, 10]])

## Boolean Indexing

In [15]:
ndarray_1d = np.array(['I', 'am', 'VN Pikachu'])
ndarray_1d

array(['I', 'am', 'VN Pikachu'], dtype='<U10')

In [19]:
ndarray_1d[[True, False, True]]

array(['I', 'VN Pikachu'], dtype='<U10')

In [20]:
ndarray_2d = np.arange(9).reshape((3,3))
ndarray_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
mask = np.eye(3).astype('bool')
mask

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [22]:
ndarray_2d[mask]

array([0, 4, 8])

## Examples

<p style = 'color:red'>select values greater than 5 in the ndarray</p>

In [24]:
np.random.randint?

In [25]:
arr = np.random.randint(1, 10, (3,3))
arr

array([[5, 5, 8],
       [8, 8, 6],
       [7, 8, 2]])

In [26]:
arr[arr > 5]

array([8, 8, 8, 6, 7, 8])

<p style = 'color:red'>select non nan values</p>

In [28]:
arr = np.array([2, np.nan, 3, np.nan, np.nan])
arr

array([ 2., nan,  3., nan, nan])

In [30]:
arr[~np.isnan(arr)]

array([2., 3.])

<p style = 'color:red'>filter out non-complex values</p>

In [31]:
arr = np.array([1, 5, 3 + 2j, 5 + 1j, 2, 3, 3 + 2j])
arr

array([1.+0.j, 5.+0.j, 3.+2.j, 5.+1.j, 2.+0.j, 3.+0.j, 3.+2.j])

In [32]:
arr[~np.iscomplex(arr)]

array([1.+0.j, 5.+0.j, 2.+0.j, 3.+0.j])

# Advanced Indexing

<https://www.gormanalysis.com/blog/python-numpy-for-your-grandma-5-1-advanced-array-indexing/>