# Save and load data with <code>np.save</code> and <code>np.load</code>

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
#save a given array to a binary file 
np.save('my_data', a)

In [6]:
np.load('my_data.npy')

array([1, 2, 3])

**`np.savez`**: save two given arrays into a single file in compressed format (.npz format) and load it. 

In [13]:
levels = [35, 33, 31]
damage = [56, 30, 57]
np.savez('tankforce', levels = levels, damage = damage)
with np.load('tankforce.npz') as data:
    print(data['levels'])
    print(data['damage'])

[35 33 31]
[56 30 57]


**`np.savetxt`**, **`np.loadtxt`**: save and load text file

In [16]:
np.savetxt('levels.txt', levels)
np.loadtxt('levels.txt')

array([35., 33., 31.])

# Loading dataset from url

## np.genfromtxt

loading iris dataset

In [1]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [6]:
iris_1d = np.genfromtxt(url, delimiter = ',')

In [7]:
iris_1d

array([[5.1, 3.5, 1.4, 0.2, nan],
       [4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3

In [8]:
iris_1d.shape

(150, 5)

In [9]:
iris_1d[5]

array([5.4, 3.9, 1.7, 0.4, nan])

# Loading and saving Text

**`np.loadtxt`**, **`np.savetxt`**

In [2]:
help(np.loadtxt)

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
  