In [2]:
import numpy as np

# np.nditer(array)

return an iterator of values of that array

In [2]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.nditer(arr)

In [4]:
for v in np.nditer(arr):
    print(v)

0
1
2
3
4
5
6
7
8


let's change the order or reading

In [5]:
for v in np.nditer(arr, order = 'F'):
    print(v)

0
3
6
1
4
7
2
5
8


# Broadcasting iteration

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b = np.array([4,5,6]).reshape((3,1))
b

array([[4],
       [5],
       [6]])

In [8]:
for x, y in np.nditer([a,b]):
    print(x, y)

1 4
2 4
3 4
1 5
2 5
3 5
1 6
2 6
3 6


# np.ndenumerate

In [3]:
for i, v in np.ndenumerate([[1,2],[3,4]]):
    print(i, v)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [4]:
np.add.reduceat?

## np.ndindex

In [3]:
z = np.arange(9).reshape((3,3))
for loc in np.ndindex(z.shape):
    print(loc)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(2, 2)
