In [2]:
import numpy as np

In [9]:
mat = np.array([
    [1,2],
    [3,4]
])

v = np.array([
    [5,6],
    [7,8]
])

inverse matrix

In [10]:
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

determinant

In [11]:
np.linalg.det(mat)

-2.0000000000000004

multiply 2 matrices

In [12]:
np.matmul(mat, v)

array([[19, 22],
       [43, 50]])

In [13]:
#equivalent
mat @ v

array([[19, 22],
       [43, 50]])

outer 

In [14]:
np.outer([1,2,3], [1,2,3])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [15]:
np.array([1,2]) @ np.array([3,4])

11

# np.linalg.solve(a, b)

solving <code> ax = b</code>

In [23]:
a = [
    [1,2],
    [2, 3]
]
b = [3, 7]

In [24]:
np.linalg.solve(a, b)

array([ 5., -1.])

# Triangle matrix

```python
np.tri
np.tril
np.tril_indices
np.tril_indices_from
np.trim_zeros
np.triu
np.triu_indices
np.triu_indices_from
```

# Eigenvalues, eigenvectors

```python
np.linalg.eig
np.linalg.eigh
np.linalg.eigvals
np.linalg.eigvalsh
```

# Decomposition

In [6]:
from numpy.linalg import qr, svd