In [1]:
import numpy as np

# np.apply_along_axis(func, axis ,arr, *arg)

let's calculate the result of max - min of each column

In [2]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.apply_along_axis(lambda column: max(column) - min(column), 0, a)

array([6, 6, 6])

let's calculate the result of mean - medium of each row

In [10]:
np.apply_along_axis(lambda row: np.mean(row) - np.median(row), 1, a)

array([0., 0., 0.])

# np.apply_over_axes(func, a, axes)