In [2]:
import numpy as np

# np.sum, np.cumsum, np.prod, np.cumprod

In [3]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
np.sum(a)

10

In [5]:
np.sum(a, axis = 1)

array([3, 7])

In [7]:
np.sum(a, axis = 1, keepdims = True)

array([[3],
       [7]])

# Trigonometric Functions

np.sin, np.cos, np.tan, np.arctan, np.arccos, np.arc, np.degrees, np.deg2rad

In [7]:
x = np.linspace(0, np.pi / 2, 5)
x

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [8]:
np.sin(x)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [11]:
np.arccos(0)

1.5707963267948966

In [13]:
np.degrees(np.pi)

180.0

# Rounding Functions

## np.around(a, decimals = 0)

In [17]:
values = np.random.rand(10) * 100
values

array([46.30301581, 27.98930071, 13.27153617, 21.06320055,  8.45905814,
       30.83299466, 99.5933316 , 72.55770767,  2.37436776, 60.3110724 ])

positive decimals, will round float part

In [18]:
np.around(values, 2)

array([46.3 , 27.99, 13.27, 21.06,  8.46, 30.83, 99.59, 72.56,  2.37,
       60.31])

negative decimals, will round integer part

In [19]:
np.around(values, -1)

array([ 50.,  30.,  10.,  20.,  10.,  30., 100.,  70.,   0.,  60.])

# np.floor(a)

In [24]:
np.floor(values)

array([46., 27., 13., 21.,  8., 30., 99., 72.,  2., 60.])

In [25]:
np.ceil(values)

array([ 47.,  28.,  14.,  22.,   9.,  31., 100.,  73.,   3.,  61.])

# np.ceil(a)