In [1]:
from numpy import matlib
import numpy as np

<code>matlib</code> will provide <code>matrix type</code>, instead of <code>ndarray type</code> 

In [2]:
matlib.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
matlib.zeros((4,5))

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
matlib.full((3,3), -1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [6]:
matlib.eye(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
np.matrix('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

In [2]:
np.matrix?