In [2]:
import numpy as np

ndarray: N-dimensional array

# Numpy.array()

In [3]:
scores = [9, 8, 10]

In [4]:
np.array(scores)

array([ 9,  8, 10])

In [5]:
np.array(scores, dtype = 'complex')

array([ 9.+0.j,  8.+0.j, 10.+0.j])

In [7]:
np.array(scores, ndmin = 2)

array([[ 9,  8, 10]])

# Numpy.fromiter

In [3]:
iterator = iter([1,2,3])
np.fromiter(iterator, dtype = np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])