In [3]:
import numpy as np

# np.arange

In [3]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

# np.linspace

In [5]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# np.logspace

create ten elements in the log scale, start from $10^1$ to $10^2$

In [7]:
np.logspace(1,2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

# np.s_

In [6]:
#remove every 2-th row, starting from 1-th row
arr = np.arange(14).reshape((-1,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [8]:
np.delete(arr, np.s_[1::2], axis = 0)

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])