In [1]:
import numpy as np

# np.set_printoptions(**kwargs)

## precision

print float 3 demcimal

In [3]:
np.set_printoptions(precision=3)

In [4]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.851, 0.007, 0.083],
       [0.002, 0.695, 0.852],
       [0.276, 0.902, 0.288],
       [0.667, 0.561, 0.741],
       [0.335, 0.751, 0.216]])

## supress

pretty print a numpy array by suppressing the scientific notation (like 1e10) to 0, 000000000001

In [7]:
np.set_printoptions(suppress=False)

In [8]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [10]:
np.set_printoptions(suppress = True, precision = 6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

## threshold

limit the number of items printed in output of numpy array

In [13]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

limit to only print 6 numbers

In [14]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])