In [1]:
import numpy as np

# np.sort, np.argsort, np.searchsorted

## np.sort(a, axis, kind, order)

In [3]:
arr = np.random.randint(0, 10, 50)
arr

array([7, 0, 1, 2, 6, 3, 2, 9, 2, 9, 1, 4, 6, 1, 4, 4, 8, 4, 9, 5, 6, 1,
       4, 8, 2, 4, 0, 9, 8, 8, 8, 6, 0, 7, 7, 7, 4, 3, 1, 5, 8, 3, 4, 2,
       1, 4, 8, 4, 4, 4])

In [7]:
np.sort(arr, kind = 'quicksort')

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9])

In [8]:
np.argsort(arr, kind = 'mergesort')

array([ 7, 11, 37, 39, 40,  6, 31, 33, 44, 46, 26, 32, 36, 38, 18, 24, 30,
        0, 10, 14, 15, 16,  5,  8, 13, 20, 41, 45,  2, 19, 49,  3, 21, 28,
       34,  1, 17, 23, 35, 42,  4,  9, 12, 22, 25, 27, 29, 43, 47, 48],
      dtype=int64)

In [10]:
arr[np.argsort(arr, kind = 'heapsort')]

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9])

In [4]:
arr_2D = arr.reshape((10,5))
arr_2D

array([[7, 0, 1, 2, 6],
       [3, 2, 9, 2, 9],
       [1, 4, 6, 1, 4],
       [4, 8, 4, 9, 5],
       [6, 1, 4, 8, 2],
       [4, 0, 9, 8, 8],
       [8, 6, 0, 7, 7],
       [7, 4, 3, 1, 5],
       [8, 3, 4, 2, 1],
       [4, 8, 4, 4, 4]])

In [13]:
#sort 2D array for each column
np.sort(arr_2D, kind = 'heapsort', axis = 0)

array([[0, 0, 0, 1, 0],
       [3, 1, 0, 2, 1],
       [4, 1, 2, 3, 3],
       [4, 1, 6, 5, 4],
       [4, 2, 8, 5, 6],
       [5, 2, 8, 7, 6],
       [5, 4, 9, 7, 7],
       [5, 5, 9, 8, 9],
       [8, 7, 9, 9, 9],
       [9, 8, 9, 9, 9]])

In [5]:
#flatten then sort 2D array
np.sort(arr_2D, axis = None)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8,
       8, 8, 9, 9, 9, 9])

## Inplace sort: **`ndarray.sort`**

In [6]:
arr

array([7, 0, 1, 2, 6, 3, 2, 9, 2, 9, 1, 4, 6, 1, 4, 4, 8, 4, 9, 5, 6, 1,
       4, 8, 2, 4, 0, 9, 8, 8, 8, 6, 0, 7, 7, 7, 4, 3, 1, 5, 8, 3, 4, 2,
       1, 4, 8, 4, 4, 4])

In [7]:
arr.sort(kind = 'heapsort')

In [8]:
arr

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8,
       8, 8, 9, 9, 9, 9])

## Sorting Structured Array


Write a NumPy program to create a structured array from given student name, height, class and their data types.  
Now sort the array on height.  
Sample Output:  
Original array:  
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )  
(b'Pit', 5, 40.11)]  
Sort by height  
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )  
(b'Nail', 6, 52.5 )]


In [9]:
dtype = np.dtype([('Name', 'S15'), ('Class', 'int'), ('Height', 'float64')])
data = [(b'James', 5, 48.5 ),
        (b'Nail', 6, 52.5 ),
        (b'Paul', 5, 42.1 ),
        (b'Pit', 5, 40.11)]

df = np.array(data, dtype = dtype)
df

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('Name', 'S15'), ('Class', '<i4'), ('Height', '<f8')])

In [10]:
np.sort(df, order = 'Height')

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('Name', 'S15'), ('Class', '<i4'), ('Height', '<f8')])

# np.lexsort

In [13]:
#Sort names: first by surname, then by name.

surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

# np.sort_complex

 sort a given complex array using the real part first, then the imaginary part

In [14]:
np.sort_complex([(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)])

array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

In [15]:
#normal sort
np.sort([(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)])

array([1.+2.j, 3.-2.j, 3.-1.j, 3.+5.j, 4.-3.j])

# np.searchsorted(a, v, kind = 'left')

kind = 'left' is equivalent bisect_left<br>
kind = 'right' is equivalent bisect_right

let create a histogram consists of 3 bins : 0-> 20, 20 -> 40, 40 -> 60

In [16]:
seq = np.random.randint(0, 60, 120)
seq

array([15, 47,  2, 42, 44,  2, 47, 41, 27, 56, 35, 24, 55, 32, 46,  0, 30,
       26, 17, 35, 34, 18, 42, 11, 45, 57, 11, 58, 16, 11, 38, 30, 43, 28,
       40, 59, 40,  3,  0, 34, 45,  4, 49, 10, 33,  5, 57, 25, 31, 44,  2,
       36, 42, 26, 15, 20,  3, 53, 54, 28,  6, 38, 37,  3, 17, 37, 22, 52,
        4, 49, 12, 30, 19,  7, 32, 55, 59, 36, 56,  4, 10, 32, 23, 11, 56,
       53, 18, 58,  1, 10, 49, 15, 43, 44, 41, 16, 29, 46, 32, 52, 18, 24,
       23, 12, 29, 31, 47, 14, 45, 30, 58, 20, 32, 35, 41, 31, 11,  3,  9,
       25])

In [18]:
np.searchsorted([0, 20, 40], seq)

array([1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 2, 2, 3, 2, 3, 0, 2, 2, 1, 2, 2, 1,
       3, 1, 3, 3, 1, 3, 1, 1, 2, 2, 3, 2, 2, 3, 2, 1, 0, 2, 3, 1, 3, 1,
       2, 1, 3, 2, 2, 3, 1, 2, 3, 2, 1, 1, 1, 3, 3, 2, 1, 2, 2, 1, 1, 2,
       2, 3, 1, 3, 1, 2, 1, 1, 2, 3, 3, 2, 3, 1, 1, 2, 2, 1, 3, 3, 1, 3,
       1, 1, 3, 1, 3, 3, 3, 1, 2, 3, 2, 3, 1, 2, 2, 1, 2, 2, 3, 1, 3, 2,
       3, 1, 2, 2, 3, 2, 1, 1, 1, 2], dtype=int64)

In [20]:
#equivalent to
np.digitize(seq, [0, 20, 40])

array([1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 2, 2, 3, 2, 3, 1, 2, 2, 1, 2, 2, 1,
       3, 1, 3, 3, 1, 3, 1, 1, 2, 2, 3, 2, 3, 3, 3, 1, 1, 2, 3, 1, 3, 1,
       2, 1, 3, 2, 2, 3, 1, 2, 3, 2, 1, 2, 1, 3, 3, 2, 1, 2, 2, 1, 1, 2,
       2, 3, 1, 3, 1, 2, 1, 1, 2, 3, 3, 2, 3, 1, 1, 2, 2, 1, 3, 3, 1, 3,
       1, 1, 3, 1, 3, 3, 3, 1, 2, 3, 2, 3, 1, 2, 2, 1, 2, 2, 3, 1, 3, 2,
       3, 2, 2, 2, 3, 2, 1, 1, 1, 2], dtype=int64)

# np.where

In [22]:
ndarray_2D = np.random.randint(-10, 10, (5,5))
ndarray_2D

array([[  8,  -9,  -6,  -5,  -7],
       [  6,   1,   2,   0,   2],
       [ -5,   8,  -6,   4,  -5],
       [  6,  -4,   5,   1, -10],
       [  7,   7,   7,   7,  -2]])

let's muliply positive number by 10, turn negative to positive number

In [24]:
np.where(ndarray_2D > 0, ndarray_2D * 10, -ndarray_2D)

array([[80,  9,  6,  5,  7],
       [60, 10, 20,  0, 20],
       [ 5, 80,  6, 40,  5],
       [60,  4, 50, 10, 10],
       [70, 70, 70, 70,  2]])

let's get the indices of values < 0

In [25]:
np.where(ndarray_2D < 0)

(array([0, 0, 0, 0, 2, 2, 2, 3, 3, 4], dtype=int64),
 array([1, 2, 3, 4, 0, 2, 4, 1, 4, 4], dtype=int64))

# np.partition

In [20]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([1, 5, 4, 8, 7, 0, 2, 3, 9, 6])

first 3 elements will be 3 smallest values

In [4]:
np.partition(arr, 3)

array([2, 1, 0, 3, 4, 5, 8, 6, 7, 9])

last 5 elements will be 5 largest values

In [6]:
np.partition(arr, -5)

array([4, 0, 1, 2, 3, 5, 8, 6, 7, 9])

# np.argpartition

In [21]:
#Write a NumPy program to sort 5 elements from beginning of a given array
arr[np.argpartition(arr, range(5))]

array([0, 1, 2, 3, 4, 5, 7, 8, 9, 6])

In [22]:
#equivalent
np.partition(arr, range(5))

array([0, 1, 2, 3, 4, 5, 7, 8, 9, 6])