In [2]:
import numpy as np

# min, max, argmin, argmax, ptp

In [2]:
np.argmin([3,1,2])

1

In [3]:
np.max([
    [1,2,3],
    [4,5,6],
    [0, 3, 11]
], axis = 0)

array([ 4,  5, 11])

In [3]:
#peak to peak distance
np.ptp([1,3,2]) #max - min

2

# mean, average, median, std, var

weighted average

In [11]:
np.average([10, 5], weights = (0.25, 0.75))

6.25

In [9]:
np.average?

# quantile, percentile

In [13]:
np.quantile?

# bincount

Note: **`bincount()`** function count number of occurrences of each value in an array of non-negative integers in the range of the array between the minimum and maximum values including the values that did not occur.

In [3]:
np.bincount([0, 1, 6, 1, 4, 1, 2, 2, 7] )

array([1, 3, 2, 0, 1, 0, 1, 1], dtype=int64)

In [4]:
np.hist?

Object `np.hist` not found.


# histogram

In [5]:
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
np.histogram(nums, bins)

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))