Reference: <https://www.gormanalysis.com/blog/python-numpy-for-your-grandma-6-1-as_strided/>

In [2]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

>Calculate the sum of window of size 3

In [5]:
n = 10
values = np.arange(10)
window_size = 3

target = as_strided(values, shape=(n - window_size + 1, window_size), strides=(values.itemsize, values.itemsize))
# target is just a view of values, so it does not cost space
target

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [6]:
target.sum(1)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

>Consider a one-dimensional array Z, build a two-dimensional array whose first row is `(Z[0],Z[1],Z[2])` and each subsequent row is shifted by 1 (last row should be `(Z[-3],Z[-2],Z[-1])` 

In [8]:
Z = np.arange(10)

as_strided(Z, shape=(8, 3), strides=(Z.itemsize, Z.itemsize))

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

>Write a function to roll window of size `k` over a 1-D array

In [9]:
def roll(arr, window_size):
    # arr must be an ndarray
    return as_strided(arr, shape=(arr.shape[0] - window_size + 1, window_size), strides=(arr.itemsize, arr.itemsize))

roll(Z, 4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

>Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [11]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 1]
   [0 0 4]
   [3 2 3]]

  [[2 1 1]
   [0 4 0]
   [2 3 1]]

  [[1 1 2]
   [4 0 4]
   [3 1 2]]

  [[1 2 1]
   [0 4 0]
   [1 2 4]]

  [[2 1 1]
   [4 0 0]
   [2 4 1]]

  [[1 1 2]
   [0 0 3]
   [4 1 1]]

  [[1 2 0]
   [0 3 2]
   [1 1 1]]

  [[2 0 2]
   [3 2 2]
   [1 1 4]]]


 [[[0 0 4]
   [3 2 3]
   [0 3 1]]

  [[0 4 0]
   [2 3 1]
   [3 1 0]]

  [[4 0 4]
   [3 1 2]
   [1 0 3]]

  [[0 4 0]
   [1 2 4]
   [0 3 0]]

  [[4 0 0]
   [2 4 1]
   [3 0 1]]

  [[0 0 3]
   [4 1 1]
   [0 1 0]]

  [[0 3 2]
   [1 1 1]
   [1 0 0]]

  [[3 2 2]
   [1 1 4]
   [0 0 1]]]


 [[[3 2 3]
   [0 3 1]
   [4 2 4]]

  [[2 3 1]
   [3 1 0]
   [2 4 2]]

  [[3 1 2]
   [1 0 3]
   [4 2 1]]

  [[1 2 4]
   [0 3 0]
   [2 1 3]]

  [[2 4 1]
   [3 0 1]
   [1 3 3]]

  [[4 1 1]
   [0 1 0]
   [3 3 4]]

  [[1 1 1]
   [1 0 0]
   [3 4 4]]

  [[1 1 4]
   [0 0 1]
   [4 4 4]]]


 [[[0 3 1]
   [4 2 4]
   [3 1 3]]

  [[3 1 0]
   [2 4 2]
   [1 3 1]]

  [[1 0 3]
   [4 2 1]
   [3 1 3]]

  [[0 3 0]
   [2 1 3]
   [1 3 1]]

  [[3 0 1]
   