**Universal functions (ufuncs)** expect a set of scalars as input and produce a set of scalars as
output.  
They are actually Python objects that encapsulate the behavior of a function.  

Universal functions are not functions
but Python objects representing functions. Universal functions have five important methods
listed as follows:

```python
1. ufunc.reduce(a[, axis, dtype, out, keepdims])
2. ufunc.accumulate(array[, axis, dtype, out])
3. ufunc.reduceat(a, indices[, axis, dtype, out])
4. ufunc.outer(A, B)
5. ufunc.at(a, indices[, b])])])
6. ufunc.at(a, indices[, b]).
```


In [46]:
import numpy as np

# Creating Universal Funcions

**`np.frompyfunc`**: take an abitrary python function and return a Numpy ufunc

```python
frompyfunc(func, nin, nout)
```

In [7]:
np.info(np.frompyfunc)

frompyfunc(func, nin, nout)

Takes an arbitrary Python function and returns a NumPy ufunc.

Can be used, for example, to add broadcasting to a built-in Python
function (see Examples section).

Parameters
----------
func : Python function object
    An arbitrary Python function.
nin : int
    The number of input arguments.
nout : int
    The number of objects returned by `func`.

Returns
-------
out : ufunc
    Returns a NumPy universal function (``ufunc``) object.

See Also
--------
vectorize : evaluates pyfunc over input arrays using broadcasting rules of numpy

Notes
-----
The returned ufunc always returns PyObject arrays.

Examples
--------
Use frompyfunc to add broadcasting to the Python function ``oct``:

>>> oct_array = np.frompyfunc(oct, 1, 1)
>>> oct_array(np.array((10, 30, 100)))
array([012, 036, 0144], dtype=object)
>>> np.array((oct(10), oct(30), oct(100))) # for comparison
array(['012', '036', '0144'],
      dtype='|S4')


Create ufunc: twos_like

In [11]:
def twos(a):
    return np.full_like(a, 2)
twos_like = np.frompyfunc(twos,1,1) #1 input parameter, 1 output parameter
twos_like([[1,2], [3,4]])

array([[array(2), array(2)],
       [array(2), array(2)]], dtype=object)

In [13]:
dir(twos_like)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

# Methods

In [17]:
a = np.arange(9)

**`ufunc.reduce`**

In [18]:
np.add.reduce(a) #equivalent np.sum

36

**`ufunc.accumulate`**

In [30]:
np.add.accumulate(a) #equivalent np.cumsum


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

**`ufunc.reduceat`**

In [32]:
np.add.reduceat(a, indices = [0,5,2,7])

array([10,  5, 20, 15], dtype=int32)

In [33]:
#step1:
a[0:5].sum()

10

In [34]:
#step2: 5 > 2 so return a[5]
a[5]

5

In [37]:
#step3:
a[2:7].sum()

20

In [38]:
#step4
a[7:].sum()

15

**`ufuncs.outer`**

In [43]:
np.multiply.outer([1,2], [1,2]) #equivalent : np.outer([1,2], [1,2])

array([[1, 2],
       [2, 4]])

In [44]:
np.add.outer([1,2], [1,2]) #adding instead of multiplying like np.multiply.outer

array([[2, 3],
       [3, 4]])

**`ufunc.at`**: Fancy indexing in-place

In [57]:
arr = np.array([1,-2,-3,5,7])

np.negative.at(arr, [1,3]) #multiply values at index 1 and 3 by -1, inplace
arr

array([ 1,  2, -3, -5,  7])

In [59]:
np.nonzero?

sum alemeent at specific indices (allow duplicated)

In [3]:
res = np.zeros(5)

np.add.at(res, [1, 3, 1, 2], [1, 1, 1, 1])

res

array([0., 2., 1., 1., 0.])