In [1]:
import numpy as np 

# ndarray.view()

In [2]:
ndarray = np.array([1,2,3])

In [4]:
b = ndarray.view()

In [5]:
id(ndarray), id(b)

(2183851156864, 2183851156704)

<b style = 'color:red'>Change value of b will also change value of <code>ndarray</code>

In [9]:
b[0] = 100`

In [10]:
b 

array([100,   2,   3])

In [12]:
ndarray

array([100,   2,   3])

<b style = 'color:red'>change the way <code>ndarray</code> "look" (e.g: changing the shape, datatype)

In [15]:
ndarray.view(dtype = 'uint')

array([100,   2,   3], dtype=uint32)

<hr>

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
#b is a view of a
#we can change the way display a via b
b = a.view()

b = b[::-1] #reverse row
b

array([[3, 4],
       [1, 2]])

In [4]:
#in array b, change value 1 to -1
b[b == 1] = -1
b

array([[ 3,  4],
       [-1,  2]])

In [5]:
#value 1 in array will also be changed to -1
a

array([[-1,  2],
       [ 3,  4]])

# np.copy

 deep copy

In [16]:
ndarray_clone = np.copy(ndarray)

In [17]:
ndarray_clone[0] = 1234

In [18]:
ndarray

array([100,   2,   3])

# View and Copy

<https://www.gormanalysis.com/blog/python-numpy-for-your-grandma-5-2-view-vs-copy/>

Indexing using integer index will return a copy. Indexing using purely slicing will always return a view