<a href = 'https://www.w3resource.com/python-exercises/numpy/basic/index.php' style='font-size:30px'>Numpy Exercises</a>

In [1]:
import numpy as np

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [2]:
np.r_[np.zeros(10), np.ones(10), np.full(10, 5)]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [3]:
np.hstack((np.zeros(10), np.ones(10), np.full(10, 5)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.concatenate((np.zeros(10), np.ones(10), np.full(10, 5)))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [14]:
ans = np.ones((10,10))
ans[1:-1, 1:-1] = 0
ans

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


Write a NumPy program to create a structured array from given student name, height, class and their data types.  
Now sort the array on height.  
Sample Output:  
Original array:  
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )  
(b'Pit', 5, 40.11)]  
Sort by height  
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )  
(b'Nail', 6, 52.5 )]


In [27]:
dtype = np.dtype([('Name', 'S15'), ('Class', 'int'), ('Height', 'float64')])
data = [(b'James', 5, 48.5 ),
        (b'Nail', 6, 52.5 ),
        (b'Paul', 5, 42.1 ),
        (b'Pit', 5, 40.11)]

df = np.array(data, dtype = dtype)
df

array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
       (b'Pit', 5, 40.11)],
      dtype=[('Name', 'S15'), ('Class', '<i4'), ('Height', '<f8')])

In [25]:
np.sort(df, order = 'Height')

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('Name', 'S15'), ('Class', '<i4'), ('Height', '<f8')])

sort by class, then height if class are equal

In [28]:
df = np.array([(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ), (b'Pit', 5, 40.11)],
             dtype = np.dtype([('Name', 'S15'), ('Class', 'int'), ('Height', 'float')]))
np.sort(df, order = ('Class', 'Height'))

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('Name', 'S15'), ('Class', '<i4'), ('Height', '<f8')])

sort by 2 array

In [29]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
idx = np.lexsort((student_id, student_height))
idx

array([4, 0, 5, 3, 6, 1, 2], dtype=int64)

In [30]:
for i in idx:
    print(student_id[i], student_height[i])

1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


Write a NumPy program to make all the elements of a given string to a numeric string of 5 digits with zeros on its left

In [70]:
s = ['2','11','234','1234', '12345']
np.char.rjust(s, width = 5, fillchar = '0')

array(['00002', '00011', '00234', '01234', '12345'], dtype='<U5')

In [71]:
#equivalent
np.char.zfill(s, 5)

array(['00002', '00011', '00234', '01234', '12345'], dtype='<U5')

Write a NumPy program to count the number of "P" in a given array, element-wise

In [73]:
s = ['Python', 'PHP', 'JS', 'examples', 'html']
np.char.count(s, 'P')

array([1, 2, 0, 0, 0])

Write a NumPy program to count the lowest index of "P" in a given array, element-wise.

In [75]:
s = ['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML']
np.char.find(s, 'P')

array([ 0,  0, -1,  4, -1])

In [76]:
#highest index search
np.char.rfind(s, 'P')

array([ 0,  2, -1,  4, -1])

Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only.

In [77]:
s = ['Python', 'PHP', 'JS', 'Examples', 'html5', '5']

In [78]:
#digit check
np.char.isdigit(s)

array([False, False, False, False, False,  True])

In [79]:
#lower check
np.char.islower(s)

array([False, False, False, False,  True, False])

In [80]:
#upper check
np.char.isupper(s)

array([False,  True,  True, False, False, False])

 Write a NumPy program to check whether each element of a given array starts with "P"

In [81]:
s = ['Python', 'PHP', 'JS' ,'examples', 'html']
np.char.startswith(s, 'P')

array([ True,  True, False, False, False])

Write a NumPy program to find the most frequent value in an array

In [100]:
v = np.random.randint(1,10, 100)

In [101]:
ix = np.bincount(v).argmax()
v[ix]

6

Write a NumPy program to get the n largest values of an array

In [99]:
v

array([9, 8, 3, 7, 2, 8, 2, 1, 5, 5, 3, 9, 1, 2, 6, 5, 5, 1, 1, 1, 8, 9,
       6, 6, 6, 7, 9, 8, 1, 9, 3, 2, 8, 7, 1, 9, 1, 3, 4, 3, 6, 1, 4, 3,
       1, 2, 3, 3, 2, 8, 6, 6, 8, 5, 8, 4, 1, 3, 4, 9, 5, 8, 3, 6, 5, 2,
       6, 1, 8, 8, 9, 4, 3, 3, 6, 3, 4, 1, 7, 6, 5, 6, 5, 8, 1, 7, 4, 2,
       8, 9, 4, 6, 9, 3, 3, 8, 3, 1, 2, 4])

In [103]:
n = 20
np.partition(v, -n)[-n:]

array([8, 8, 8, 8, 9, 8, 8, 9, 8, 9, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9])

Write a NumPy program to add a border (filled with 0's) around an existing array.

In [107]:
arr = np.ones((5,5))
np.pad(arr, pad_width=1, mode = 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [121]:
a = np.array([[1,2], [3,4]])
np.nonzero(a > 3)

(array([1], dtype=int64), array([1], dtype=int64))

Create an immutable array

In [5]:
x = np.zeros(10)
x.flags.writeable = False

In [8]:
#x[1] = -1

write a function to remove negative values:

In [9]:
a = np.array([-1,2,-3,4])

In [17]:
np.delete(a, np.where(a < 0))

array([2, 4])

 remove all rows in a NumPy array that contain non-numeric values

In [22]:
a = np.array([[1,2], [3, np.nan], [5,6], [np.nan, np.nan]])
np.delete(a, np.nonzero(np.isnan(a).any(axis = 1)), axis = 0)

array([[1., 2.],
       [5., 6.]])

In [19]:
np.isnan(a)

array([[False, False],
       [False,  True],
       [False, False],
       [ True,  True]])

count the number of times 5 appears:

In [34]:
a = np.random.randint(1,10, 100)
np.count_nonzero(a == 5)

11

remove nan values from a given array

In [35]:
a = np.array([1, np.nan, 2])
a[~np.isnan(a)]

array([1., 2.])

In [37]:
np.delete(a, np.where(np.isnan(a)))

array([1., 2.])

 find indices of elements equal to zero in a NumPy array

In [38]:
a = [0,1,0,2,0,0]
np.nonzero(a)

(array([1, 3], dtype=int64),)

calculate averages without NaNs along a given array.

In [40]:
arr1 = np.array([[10, 20 ,30], [40, 50, np.nan], [np.nan, 6, np.nan], [np.nan, np.nan, np.nan]])
print("Original array:")
print(arr1)
temp = np.ma.masked_array(arr1,np.isnan(arr1))
result = np.mean(temp, axis=1)
print("Averages without NaNs along the said array:")
print(result.filled(np.nan))

Original array:
[[10. 20. 30.]
 [40. 50. nan]
 [nan  6. nan]
 [nan nan nan]]
Averages without NaNs along the said array:
[20. 45.  6. nan]


swap 2 columns

```python
a[:, [1,2]] = a[:, [2,1]] #swap column 1 vs 2 (0-based)
```

 Write a NumPy program to create a new vector with 2 consecutive 0 between two values of a given vector.

In [50]:
a = np.array([1,2,3])

np.vstack((np.expand_dims(a,0), np.zeros((2,3)))).T.flatten()

array([1., 0., 0., 2., 0., 0., 3., 0., 0.])

In [51]:
a

array([1, 2, 3])

In [52]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])